// GENERATED by platform_cloud-components/scripts/distribute.mjs — DO NOT EDIT.

/** Execution params for the PointCloudConverter cloud component. */
export interface LasToPotreeParams {
  /** Action (SIMPLE|PLAN|BUILD|MERGE) */
  action?: string;
  /** LAS Point Cloud File ID */
  fileId: string;
  /** Split level (PLAN) */
  K?: number;
  /** Global grid JSON (BUILD/MERGE) */
  grid?: string;
  /** Cell name (BUILD) */
  cell?: string;
  /** Tile descriptors JSON (MERGE) */
  tiles?: string;
  /** Shared entry item id (BUILD/MERGE) */
  entryId?: string;
  /** Cell LAS shard hidden-file ids JSON (BUILD cell-file mode) */
  shards?: string;
}

/**
 * **PointCloudConverter** — Convert a LAS point cloud into a streamable Potree 2.0 octree.
 *
 * Reads an uploaded .las and builds a Potree 2.0 octree (metadata.json + hierarchy.bin + chopped octree pieces), published as one visible `.potree` entry whose hidden files hold the streamed chunks. The viewer byte-ranges those chunks, so a cloud opens without downloading it whole.
 * 
 * The conversion itself lives in @thatopen-platform/components-beta (realityCapture); this component is only the platform I/O around it.
 *
 * Notes:
 * - PLAN/BUILD/MERGE is a MEMORY workaround, not a speed feature — a billion-point cloud cannot fit in one worker. It needs many chained executions, and the platform's file API is whole-file-only (it ignores HTTP Range) at ~7 MB/s, so a 50GB / 2B-point cloud would spend ~9 hours just moving bytes, most of it network. Convert those OFFLINE and upload the .potree directly.
 * - LAZ is not supported (it is compressed; the LASF signature check rejects it).
 *
 * Accepts `.las` → produces `.potree`.
 *
 * The execution's `resultMessage` carries the produced file id as
 * `[potreeFileId=<id>]`; use {@link LasToPotree.parseResult} rather than re-inventing the regex.
 */
export const LasToPotree = {
  /** The name the component is PROVISIONED under (what `listComponents({projectId})` returns). */
  publishedAs: "PointCloudConverter",
  /** The repo/slug name it is published from. */
  slug: "las-to-potree",
  /** Source extensions this converts. */
  accepts: ["las"] as const,
  /** The extension it produces. */
  produces: "potree",
  /** Valid `action` values. */
  actions: ["SIMPLE", "PLAN", "BUILD", "MERGE"] as const,
  /** Hard limits — exceed them and the component FAILS with a message, it does not silently degrade. */
  limits: {"SIMPLE":{"maxPoints":60000000,"reason":"The whole cloud is held in one worker (~7-8GB, no disk). Above this the component FAILS with a clear message rather than dying silently."}},
  /**
   * Pull the produced file id out of an execution's `resultMessage`.
   * Returns null when the message carries none (e.g. the execution failed).
   */
  parseResult(resultMessage: string | undefined | null): string | null {
    const m = /potreeFileId=([^\]\s]+)/.exec(resultMessage ?? "");
    return m ? m[1] : null;
  },
} as const;
