// GENERATED by platform_cloud-components/scripts/distribute.mjs — DO NOT EDIT.

/** Execution params for the GaussianSplatConverter cloud component. */
export interface SplatToFqParams {
  /** Gaussian-Splat PLY File ID */
  fileId: string;
  /** Gaussian scale (metric calibration, default 1) */
  gaussianScale?: string;
}

/**
 * **GaussianSplatConverter** — Convert a 3D Gaussian Splat PLY into a streamable FQ LOD tree.
 *
 * Reads an uploaded .ply (plain INRIA 3DGS, or a PlayCanvas compressed.ply) and builds an octree of flat-quant (FQ) LOD nodes, published as one visible `.splat` entry whose hidden files hold the streamed nodes. The viewer fetches only the nodes it needs at the LOD it needs.
 * 
 * Pure CPU: no GPU, no WebGPU, no WebP, no k-means — which is what lets it run in a cloud worker at all (the splat-transform toolchain it replaces requires WebGPU). The codec and converter live in @thatopen-platform/components-beta (realityCapture); this component is only the platform I/O around it.
 *
 * Notes:
 * - gaussianScale is a METRIC CALIBRATION, not a quality knob: reality-capture splats are non-metric, so this scales them to real-world metres. It is PER-CAPTURE (alcardete calibrates to ~70) — default 1, and recalibrate in the viewer.
 * - Spherical harmonics (view-dependent colour) are NOT carried: the FQ codec stores a flat RGBA per splat, and the renderer evaluates no SH. A capture therefore renders matte compared to its source. This is a known fidelity gap, not a bug.
 *
 * Accepts `.ply` → produces `.splat`.
 *
 * The execution's `resultMessage` carries the produced file id as
 * `[splatFileId=<id>]`; use {@link SplatToFq.parseResult} rather than re-inventing the regex.
 */
export const SplatToFq = {
  /** The name the component is PROVISIONED under (what `listComponents({projectId})` returns). */
  publishedAs: "GaussianSplatConverter",
  /** The repo/slug name it is published from. */
  slug: "splat-to-fq",
  /** Source extensions this converts. */
  accepts: ["ply"] as const,
  /** The extension it produces. */
  produces: "splat",
  /**
   * Pull the produced file id out of an execution's `resultMessage`.
   * Returns null when the message carries none (e.g. the execution failed).
   */
  parseResult(resultMessage: string | undefined | null): string | null {
    const m = /splatFileId=([^\]\s]+)/.exec(resultMessage ?? "");
    return m ? m[1] : null;
  },
} as const;
