/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Built-in component types and runtime stubs.
 * Auto-generated by built-in-components/scripts/distribute.mjs
 */

import type * as BUI from '@thatopen/ui';

/**
 * Built-in component that structures a ThatOpen Platform application.
 *
 * AppManager creates the app shell: a content grid with named element
 * slots arranged by CSS grid layouts, and an optional sidebar that lets
 * the user switch between layouts.
 *
 * Usage:
 * 1. Call {@link init} with icons, a grid configuration callback, and an optional container.
 * 2. Optionally set {@link showSidebar} at any point after init.
 */
declare class _AppManager<TApp extends App = App> {
    static readonly uuid: "2e32d873-02c9-421c-8743-d8a5ca6ad38a";
    enabled: boolean;
    private _icons;
    private _iconsSet;
    private _grid;
    private _initialized;
    private _sidebar;
    private _client;
    private _projectData;
    private _lazySetups;
    get icons(): IconsOf<TApp>;
    /**
     * The underlying `<bim-grid>` element.
     * Available after {@link init} has been called.
     */
    get grid(): AppGrid<TApp> | null;
    get client(): EngineServicesClient;
    get projectData(): ProjectData;
    /**
     * Shows or hides the layout-switching sidebar.
     * Can be set at any point after {@link init} has been called.
     */
    get showSidebar(): boolean;
    set showSidebar(value: boolean);
    /**
     * Initialise the app: resolve client context, process icons, mount the DOM, and invoke the grid configuration callback.
     */
    init(config: AppInitConfig<TApp>): Promise<void>;
    addSetup(uuid: string, fn: ComponentSetup): void;
    private _registerLazySetup;
    private injectStyles;
}

/**
 * Built-in component that structures a ThatOpen Platform application.
 *
 * AppManager creates the app shell: a content grid with named element
 * slots arranged by CSS grid layouts, and an optional sidebar that lets
 * the user switch between layouts.
 *
 * Usage:
 * 1. Call {@link init} with icons, a grid configuration callback, and an optional container.
 * 2. Optionally set {@link showSidebar} at any point after init.
 */
export type AppManager = InstanceType<typeof _AppManager>;
/**
 * Built-in component that structures a ThatOpen Platform application.
 *
 * AppManager creates the app shell: a content grid with named element
 * slots arranged by CSS grid layouts, and an optional sidebar that lets
 * the user switch between layouts.
 *
 * Usage:
 * 1. Call {@link init} with icons, a grid configuration callback, and an optional container.
 * 2. Optionally set {@link showSidebar} at any point after init.
 */
export const AppManager = { uuid: '2e32d873-02c9-421c-8743-d8a5ca6ad38a' } as typeof _AppManager & { uuid: '2e32d873-02c9-421c-8743-d8a5ca6ad38a' };

/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
declare class _HelloWorld {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "2c4ae432-fc24-43e9-9783-0c960c674e96";
    enabled: boolean;
    readonly name = "HelloWorld";
    constructor(components: any);
    /**
     * Returns a greeting message and logs it to the console.
     * @param who - The name to greet. Defaults to `"World"`.
     */
    greet(who?: string): string;
}
/**
 * PlatformComponents.import() expects a `main` variable in scope with
 * a `componentDefinition` property pointing to the OBC.Component class.
 * The IIFE build (name: 'main') assigns this to `var main = ...`.
 */

/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
export type HelloWorld = InstanceType<typeof _HelloWorld>;
/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
export const HelloWorld = { uuid: '2c4ae432-fc24-43e9-9783-0c960c674e96' } as typeof _HelloWorld & { uuid: '2c4ae432-fc24-43e9-9783-0c960c674e96' };

declare class _UIManager<TCustom extends UICustomShape = UICustomShape> {
    static readonly uuid: "234f1416-528d-452a-9cc9-a16c5239b2eb";
    enabled: boolean;
    readonly name = "UIManager";
    readonly builtIn: UIDataMap<BuiltinShape>;
    readonly custom: UIDataMap<TCustom>;
    constructor(components: any);
    private registerBuiltInTemplate;
    registerTemplate<K extends keyof TCustom & string>(name: K, config: {
        template: BUI.StatefullComponent<TCustom[K]['state']>;
        onInstanceCreated?: (item: [TCustom[K]['type'], BUI.UpdateFunction<TCustom[K]['state']>, BUI.ComponentUtils<TCustom[K]['state']>]) => void;
    }): void;
}

export type UIManager = InstanceType<typeof _UIManager>;
export const UIManager = { uuid: '234f1416-528d-452a-9cc9-a16c5239b2eb' } as typeof _UIManager & { uuid: '234f1416-528d-452a-9cc9-a16c5239b2eb' };

/**
 * Built-in component that creates 3D viewports with a pre-configured
 * world (scene, camera, renderer) and fragments manager.
 *
 * ViewportManager is a factory: each call to {@link create} returns a
 * new independent viewport with its own world. The component tracks all
 * created instances and cleans them up on {@link dispose}.
 *
 * @example
 * ```ts
 * const viewports = components.get(ViewportManager);
 * const { element, world } = await viewports.create();
 *
 * // Use `element` as a slot in AppManager
 * app.setup = {
 *   elements: { viewer: element },
 *   layouts: { Main: { template: `"viewer" 1fr / 1fr` } },
 * };
 * ```
 */
declare class _ViewportsManager {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "def81d43-6b44-4f4a-9c08-7649486112a4";
    enabled: boolean;
    readonly name = "ViewportManager";
    private _instances;
    private _fragmentsInitialized;
    /**
     * Creates a new viewport instance with its own world, scene, camera,
     * and renderer. Fragments manager is initialised automatically on
     * the first call.
     *
     * @param config - Optional visual configuration for the viewport.
     * @returns A {@link ViewportInstance} containing the DOM element and world.
     */
    create(config?: ViewportConfig): Promise<ViewportInstance>;
    private setupFloatingGrid;
    /**
     * Disposes all created viewport instances and their worlds.
     */
    dispose(): void;
    /**
     * Initialises the fragments manager if not yet done, and wires up
     * model loading for the given world.
     */
    private _initFragments;
}

/**
 * Built-in component that creates 3D viewports with a pre-configured
 * world (scene, camera, renderer) and fragments manager.
 *
 * ViewportManager is a factory: each call to {@link create} returns a
 * new independent viewport with its own world. The component tracks all
 * created instances and cleans them up on {@link dispose}.
 *
 * @example
 * ```ts
 * const viewports = components.get(ViewportManager);
 * const { element, world } = await viewports.create();
 *
 * // Use `element` as a slot in AppManager
 * app.setup = {
 *   elements: { viewer: element },
 *   layouts: { Main: { template: `"viewer" 1fr / 1fr` } },
 * };
 * ```
 */
export type ViewportsManager = InstanceType<typeof _ViewportsManager>;
/**
 * Built-in component that creates 3D viewports with a pre-configured
 * world (scene, camera, renderer) and fragments manager.
 *
 * ViewportManager is a factory: each call to {@link create} returns a
 * new independent viewport with its own world. The component tracks all
 * created instances and cleans them up on {@link dispose}.
 *
 * @example
 * ```ts
 * const viewports = components.get(ViewportManager);
 * const { element, world } = await viewports.create();
 *
 * // Use `element` as a slot in AppManager
 * app.setup = {
 *   elements: { viewer: element },
 *   layouts: { Main: { template: `"viewer" 1fr / 1fr` } },
 * };
 * ```
 */
export const ViewportsManager = { uuid: 'def81d43-6b44-4f4a-9c08-7649486112a4' } as typeof _ViewportsManager & { uuid: 'def81d43-6b44-4f4a-9c08-7649486112a4' };
