/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars */
/**
 * Built-in component types and runtime stubs.
 * Auto-generated by platform_builtin-components/scripts/distribute-types.mjs
 */

import type * as OBC from '@thatopen/components';
import type * as THREE from 'three';
import type { EngineServicesClient, Item, ItemFolder, ItemVersion, PlatformClient } from '../';

export interface CDEContext {
    client: PlatformClient;
    projectId: string;
}
export interface CDEUserPermissions {
    canRead: boolean;
    canCreate: boolean;
    canUpdate: boolean;
    canDelete: boolean;
    canManage: boolean;
}
export type CDEMetadataValue = string | number | boolean | null;
export interface CDENamingSegment {
    key: string;
    config?: {
        transform: (value: CDEMetadataValue) => string;
    };
}
export interface CDENamingSchema {
    separator: string;
    segments: CDENamingSegment[];
}
export interface CDEFile extends Omit<Item, 'creatingUser'> {
    createdBy: string;
    metadata: Record<string, CDEMetadataValue>;
    versions?: ItemVersion[];
    /** Tag of the file's current version (set by CDEManager from the loaded version). */
    versionTag?: string;
}
export interface CDEMetadataField {
    type: "string" | "number" | "boolean" | "list";
    description?: string;
    required?: boolean;
    label: string;
    icon?: string;
    options?: {
        value: string | number | boolean;
        label: string;
    }[];
}
export type CDEMetadataSchema = Record<string, CDEMetadataField>;
export interface CDEFileActivity {
    user: string;
    action: string;
    timestamp: string;
}
export interface CDEFileHistoryEntry {
    fileId: string;
    activity: CDEFileActivity[];
}
export interface CDEMetadataView {
    id: string;
    name: string;
    fields: string[];
}
export type CDEPendingMetadata = Record<string, CDEMetadataValue>;
export type CDEPendingMetadataSchemaEdits = Record<string, CDEMetadataField | null>;
export type FolderPendingChange = {
    kind: "create";
    tempId: string;
    name: string;
    parentId: string | null;
} | {
    kind: "rename";
    folderId: string;
    name: string;
} | {
    kind: "archive";
    folderId: string;
};
export type FolderPendingChanges = FolderPendingChange[];
export type CDEViewFileStatus = "loading" | "ready" | "failed" | "cancelled";
export type CDEMachineState = {
    kind: "idle";
} | {
    kind: "loading";
} | {
    kind: "preparing";
    files: CDEFile[];
} | {
    kind: "selected";
    files: CDEFile[];
} | {
    kind: "viewing";
    files: CDEFile[];
    fileStatus: Record<string, CDEViewFileStatus>;
    selectedFiles?: CDEFile[];
} | {
    kind: "editing";
    files: CDEFile[];
    pendingMetadata: CDEPendingMetadata;
} | {
    kind: "saving";
    files: CDEFile[];
    pendingMetadata: CDEPendingMetadata;
} | {
    kind: "deleting";
    files: CDEFile[];
} | {
    kind: "configuringMetadataSchema";
    pendingEdits: CDEPendingMetadataSchemaEdits;
} | {
    kind: "savingMetadataSchema";
    pendingEdits: CDEPendingMetadataSchemaEdits;
} | {
    kind: "configuringMetadataViews";
    pendingViews: CDEMetadataView[];
} | {
    kind: "savingMetadataViews";
    pendingViews: CDEMetadataView[];
} | {
    kind: "dragging";
    files: CDEFile[];
    sourceFolderId: string | null;
    previousState: CDEMachineState;
} | {
    kind: "movingFiles";
    files: CDEFile[];
    targetFolderId: string;
} | {
    kind: "draggingFolder";
    folderId: string;
    parentFolderId: string | null;
    previousState: CDEMachineState;
} | {
    kind: "movingFolder";
    folderId: string;
    targetFolderId: string | null;
} | {
    kind: "editingFolders";
    pendingChanges: FolderPendingChanges;
} | {
    kind: "savingFolderChanges";
    pendingChanges: FolderPendingChanges;
} | {
    kind: "editingFiles";
    pendingEdits: Record<string, Record<string, CDEMetadataValue>>;
    pendingArchives: string[];
    pendingRenames: Record<string, string>;
    previousState: {
        kind: "idle";
    } | {
        kind: "selected";
        files: CDEFile[];
    };
} | {
    kind: "savingFiles";
    pendingEdits: Record<string, Record<string, CDEMetadataValue>>;
    pendingArchives: string[];
    pendingRenames: Record<string, string>;
    previousState: {
        kind: "idle";
    } | {
        kind: "selected";
        files: CDEFile[];
    };
} | {
    kind: "error";
    reason: string;
    previous: CDEMachineState;
};
export type CDEMachineEvent = {
    type: "LOAD";
} | {
    type: "UPLOAD";
} | {
    type: "DOWNLOAD";
} | {
    type: "SELECT";
    files: CDEFile[];
} | {
    type: "DESELECT";
} | {
    type: "VIEW";
} | {
    type: "ADD_TO_VIEW";
    file: CDEFile;
} | {
    type: "REMOVE_FROM_VIEW";
    fileId: string;
} | {
    type: "CLOSE_VIEW";
} | {
    type: "SET_VIEW_FILE_STATUS";
    fileId: string;
    status: CDEViewFileStatus;
} | {
    type: "START_EDIT";
} | {
    type: "UPDATE_METADATA";
    key: string;
    value: CDEMetadataValue;
} | {
    type: "SAVE";
} | {
    type: "CANCEL_EDIT";
} | {
    type: "ARCHIVE_FILE";
} | {
    type: "START_CONFIGURE_METADATA_SCHEMA";
} | {
    type: "ADD_METADATA_FIELD";
} | {
    type: "UPDATE_METADATA_FIELD";
    key: string;
    value: CDEMetadataField;
} | {
    type: "DELETE_METADATA_FIELD";
    key: string;
} | {
    type: "RESTORE_METADATA_FIELD";
    key: string;
} | {
    type: "SAVE_METADATA_SCHEMA";
} | {
    type: "CANCEL_CONFIGURE_METADATA_SCHEMA";
} | {
    type: "START_DRAG";
    files: CDEFile[];
    sourceFolderId: string | null;
} | {
    type: "END_DRAG";
} | {
    type: "DROP_FILES";
    targetFolderId: string | null;
} | {
    type: "START_FOLDER_DRAG";
    folderId: string;
    parentFolderId: string | null;
} | {
    type: "END_FOLDER_DRAG";
} | {
    type: "DROP_FOLDER";
    targetFolderId: string | null;
} | {
    type: "START_EDIT_FILES";
} | {
    type: "UPDATE_FILE_METADATA";
    fileId: string;
    key: string;
    value: CDEMetadataValue;
} | {
    type: "REVERT_FILE_METADATA";
    fileId: string;
} | {
    type: "ARCHIVE_FILE_EDIT";
    fileId: string;
} | {
    type: "UNARCHIVE_FILE_EDIT";
    fileId: string;
} | {
    type: "RENAME_FILE";
    fileId: string;
    name: string;
} | {
    type: "RENAME_FILE_IMMEDIATE";
    fileId: string;
    name: string;
} | {
    type: "SAVE_FILE_EDITS";
} | {
    type: "CANCEL_EDIT_FILES";
} | {
    type: "START_EDIT_FOLDERS";
} | {
    type: "ADD_FOLDER";
    tempId: string;
    name: string;
    parentId: string | null;
} | {
    type: "RENAME_FOLDER";
    folderId: string;
    name: string;
} | {
    type: "ARCHIVE_FOLDER";
    folderId: string;
} | {
    type: "SAVE_FOLDER_CHANGES";
} | {
    type: "CANCEL_FOLDER_CHANGES";
} | {
    type: "RESET_FOLDER";
    folderId: string;
} | {
    type: "START_CONFIGURE_METADATA_VIEWS";
} | {
    type: "ADD_METADATA_VIEW";
} | {
    type: "UPDATE_METADATA_VIEW";
    id: string;
    view: CDEMetadataView;
} | {
    type: "DELETE_METADATA_VIEW";
    id: string;
} | {
    type: "SAVE_METADATA_VIEWS";
} | {
    type: "CANCEL_CONFIGURE_METADATA_VIEWS";
} | {
    type: "SET_ACTIVE_METADATA_VIEW";
    id: string | null;
} | {
    type: "SET_GROUPS_VIEW_MODE";
    mode: "groups" | "metadata";
} | {
    type: "FAIL";
    reason: string;
} | {
    type: "DISMISS";
};

declare class _CDEManager extends OBC.Component implements OBC.Transitionable<CDEMachineState, CDEMachineEvent> {
    static readonly uuid: "a3f82c1d-5b74-4e9a-bc30-d7e12f894a61";
    readonly onFilesChanged: OBC.Event<CDEFile[]>;
    readonly onFoldersChanged: OBC.Event<ItemFolder[]>;
    readonly onPermissionsChanged: OBC.Event<CDEUserPermissions>;
    readonly onSelectedGroupChanged: OBC.Event<string | null>;
    readonly onMachineStateChanged: OBC.Event<CDEMachineState>;
    readonly onMetadataViewsChanged: OBC.Event<CDEMetadataView[]>;
    readonly onGroupsViewModeChanged: OBC.Event<"groups" | "metadata">;
    readonly onMetadataGroupChanged: OBC.Event<Record<string, string> | null>;
    readonly onDownloadReady: OBC.Event<{
        blob: Blob;
        filename: string;
    }>;
    readonly onUploadCompleted: OBC.Event<{
        created: CDEFile[];
        versioned: CDEFile[];
    }>;
    readonly onFolderChangesCompleted: OBC.Event<{
        created: number;
        renamed: number;
        archived: number;
    }>;
    readonly onFilesMovedCompleted: OBC.Event<{
        files: CDEFile[];
        targetFolderName: string | null;
    }>;
    readonly onRenameCompleted: OBC.Event<{
        success: boolean;
        error?: string;
    }>;
    readonly onFolderMovedCompleted: OBC.Event<{
        folderName: string;
        targetFolderName: string | null;
    }>;
    readonly onShowArchivedChanged: OBC.Event<boolean>;
    readonly onRestoreCompleted: OBC.Event<{
        files?: CDEFile[];
        folder?: ItemFolder;
    }>;
    readonly onUploadStarted: OBC.Event<{
        count: number;
    }>;
    readonly onIfcConversionStarted: OBC.Event<{
        file: CDEFile;
    }>;
    readonly onIfcConversionProgress: OBC.Event<{
        file: CDEFile;
        progress: number;
    }>;
    readonly onIfcConversionCompleted: OBC.Event<{
        file: CDEFile;
        success: boolean;
        error?: string;
    }>;
    /** Fires when `_derivedFileIds` finishes a (re)sync — consumers that filter
     *  or resolve by source↔derived link (e.g. `top-files-panel` hiding an
     *  already-linked `.frag` row) should reload on this, since it can complete
     *  after `onFilesChanged` already fired with the (still unsynced) list. */
    readonly onDerivedFileIdsChanged: OBC.Event<Record<string, string>>;
    readonly conversionProgress: Map<string, number>;
    enabled: boolean;
    projectName: string;
    missingMetadataPlaceholder: string;
    availableColumns: Set<string>;
    visibleColumns: Set<string>;
    ctx?: CDEContext;
    private _machineState;
    private _activeUploads;
    private _showArchived;
    private _preArchivedViewMode;
    private _archivedFiles;
    private _archivedFolders;
    private _archivedLoaded;
    viewerGroups: {
        extensions: string[];
        multiple?: boolean;
    }[];
    get viewableExtensions(): Set<string>;
    private _files;
    /** ifcFileId → its linked derivedFileId (FRAG today; other source formats
     *  once they get a converter too), read from each IFC's own version
     *  metadata. Kept as an in-memory cache — synced by `_syncDerivedFileIds`
     *  whenever `_files` is (re)set, or right after a conversion succeeds —
     *  rather than fetched live per call, so `resolveViewFile` can stay a plain
     *  synchronous lookup (same contract as before, no ripple into
     *  `sendMachineEvent`'s callers). */
    private _derivedFileIds;
    private _folders;
    private _fileHistory;
    private _metadataSchema;
    private _metadataViews;
    private _activeMetadataViewId;
    private _groupsViewMode;
    private _selectedGroup;
    private _selectedMetadataGroup;
    private _namingSchema;
    cacheMaxBytes: number;
    cacheExtensions: Set<string>;
    private _fileCache;
    private _fileCacheBytes;
    private _dedup;
    private _cacheKey;
    private _isCacheable;
    private _addToCache;
    downloadFile(file: CDEFile): Promise<ArrayBuffer>;
    private _permissions;
    private _projectDataFolderId;
    private _appFolderIds;
    private _excludedFolderIds;
    private _projectMembers;
    get projectMembers(): {
        fullName: string;
        email: string;
        role: string;
    }[];
    get userPermissions(): CDEUserPermissions;
    query: string | null;
    get machineState(): CDEMachineState;
    get files(): CDEFile[];
    set files(value: CDEFile[]);
    /** ifcFileId → derivedFileId — see `_derivedFileIds`. */
    get derivedFileIds(): Record<string, string>;
    get folders(): ItemFolder[];
    set folders(value: ItemFolder[]);
    get showArchived(): boolean;
    set showArchived(value: boolean);
    get fileHistory(): CDEFileHistoryEntry[];
    set fileHistory(value: CDEFileHistoryEntry[]);
    get metadataSchema(): CDEMetadataSchema;
    set metadataSchema(value: CDEMetadataSchema);
    get selectedGroup(): string | null;
    set selectedGroup(value: string | null);
    get metadataViews(): CDEMetadataView[];
    get activeMetadataViewId(): string | null;
    get activeMetadataView(): CDEMetadataView | null;
    get groupsViewMode(): "groups" | "metadata";
    get selectedMetadataGroup(): Record<string, string> | null;
    set selectedMetadataGroup(value: Record<string, string> | null);
    get visibleFiles(): CDEFile[];
    get namingSchema(): CDENamingSchema | null;
    constructor(components: OBC.Components);
    hasViewer(extension: string): boolean;
    private _groupOf;
    private _sameGroup;
    canView(files: CDEFile[]): boolean;
    canAddToView(files: CDEFile[]): boolean;
    setNamingSchema(schema: CDENamingSchema): void;
    buildFileName(file: CDEFile): string;
    getSelectedFiles(): CDEFile[];
    getActivity(fileId: string): CDEFileActivity[];
    updateFilesMetadata(fileIds: string[], updates: Record<string, string>): Promise<void>;
    readProjectData(app: string, filename: string): Promise<any>;
    writeProjectData(app: string, filename: string, data: unknown): Promise<string>;
    private _ensureProjectDataFolder;
    private _ensureAppFolder;
    private _loadPermissions;
    loadFolders(): Promise<void>;
    createFolder(name: string, parentId?: string): Promise<ItemFolder>;
    getUserId(): Promise<string | undefined>;
    loadUserConfig(): Promise<{
        visibleColumns?: string[];
        metadataViews?: CDEMetadataView[];
        hideDerivedFiles?: boolean;
    } | null>;
    saveUserConfig(config: {
        visibleColumns?: string[];
        metadataViews?: CDEMetadataView[];
        hideDerivedFiles?: boolean;
    }): Promise<string | undefined>;
    loadMetadataSchema(): Promise<void>;
    initMetadataViews(views: CDEMetadataView[], activeId: string | null): void;
    loadArchivedItems(): Promise<void>;
    restoreFiles(files: CDEFile[]): Promise<void>;
    restoreFolder(folderId: string): Promise<void>;
    detectConflicts(files: File[]): {
        file: File;
        existing: CDEFile;
    }[];
    checkMoveConflicts(files: CDEFile[], targetFolderId: string | null): {
        file: CDEFile;
        existing: CDEFile;
    }[];
    /** Which file to actually load when the user views `file` — its linked FRAG
     *  if it has one, else the IFC itself. Reads `_derivedFileIds` (the IFC's
     *  own version metadata, kept in sync — see `_syncDerivedFileIds`), NOT a
     *  name+folder match anymore. Stays synchronous: `_derivedFileIds` is a
     *  pre-synced in-memory cache, so this is a plain lookup, keeping the
     *  contract every existing caller (`sendMachineEvent`'s `VIEW` case,
     *  `top-files-panel`'s "add to view" actions) already relies on. */
    resolveViewFile(file: CDEFile): CDEFile;
    /** Populates `_derivedFileIds` from every IFC's own version metadata — the
     *  source of truth for the IFC↔FRAG link (same mechanism as `models-list`'s
     *  `_syncDerivedFileIds`). Reads the unified `derivedFileId` key, falling
     *  back to the legacy `fragmentsFileId` key that `IfcFragmenter` still
     *  stamps until it's updated (see issue #3, Task 3). Called whenever
     *  `_files` is (re)set and right after a conversion succeeds — never
     *  cached indefinitely, so a reconversion or manual metadata edit is picked
     *  up on the next sync instead of going stale. */
    private _syncDerivedFileIds;
    private _saveConversionIndex;
    private _loadConversionIndex;
    private _resumePendingConversions;
    /** Cached id of the IfcFragmenter component, resolved by name for this session. */
    private _ifcFragmenterId?;
    /**
     * Resolves the platform IFC→FRAG cloud component's id by its stable name
     * (`IfcFragmenter`) within the current project, so it works across dev/prod
     * without a hardcoded id. Cached for the session. Returns `undefined` if no
     * such component is available in the project.
     */
    private _resolveIfcFragmenterId;
    private _triggerIfcConversions;
    uploadFiles(files: File[], folderId?: string | null, options?: {
        forceNew?: boolean;
    }): Promise<void>;
    sendMachineEvent(event: CDEMachineEvent): void;
    private _transition;
    private _getAllArchivedIds;
    private _collectTempDescendants;
    private _saveFolderChanges;
    private _moveFolder;
    moveFiles(files: CDEFile[], targetFolderId: string | null): Promise<void>;
    private _moveFiles;
    private _resolveFullName;
    private _prepareDownload;
    private _saveMetadataSchema;
    private _resolveKeys;
    private _saveFileMetadata;
    private _renameFileImmediate;
    private _saveFileEdits;
    private _applyMetadataEdits;
    private _applyMetadataSchemaEdits;
    private _saveMetadataViews;
    private _archiveFiles;
}

export type CDEManager = InstanceType<typeof _CDEManager>;
export const CDEManager = { uuid: 'a3f82c1d-5b74-4e9a-bc30-d7e12f894a61' } as typeof _CDEManager & { uuid: 'a3f82c1d-5b74-4e9a-bc30-d7e12f894a61' };

export type ClashStatus = "new" | "active" | "resolved" | "acknowledged";
export type ClashType = "hard" | "clearance";
export interface ClashElement {
    guid: string;
    name: string;
    localId: number;
    modelId: string;
}
export interface ClashQueryFilter {
    categories?: string[];
    attributes?: {
        aggregation?: 'exclusive' | 'inclusive';
        queries: Array<{
            name: string;
            value?: string | string[] | number | boolean;
            type?: string;
            negate?: boolean;
        }>;
    };
    relation?: {
        name: string;
        query?: ClashQueryFilter;
    };
}
export interface ClashQuery {
    id: string;
    name: string;
    modelFileIds: string[];
    /** Filter conditions. Omit or leave empty to match all elements with geometry. */
    query?: ClashQueryFilter;
}
export interface ClashMatrix {
    id: string;
    name: string;
    /** Ordered list of query IDs — index order = priority (0 = most constrained). */
    queryIds: string[];
    /** Active cell job IDs (subset of upper-triangle pairs). */
    jobIds: string[];
    /** Active upper-triangle pair keys in the form "queryAId:queryBId". */
    activePairs: string[];
    /** Clash type applied to all jobs generated by this matrix. Defaults to 'hard'. */
    jobType?: ClashType;
    /** Clearance tolerance in metres. Only used when jobType is 'clearance'. */
    tolerance?: number;
}
export interface ClashJob {
    id: string;
    name: string;
    type: ClashType;
    queryAId: string;
    queryBId: string;
    matrixId?: string;
    /** Clearance tolerance in metres. Only present when type is 'clearance'. */
    tolerance?: number;
}
export interface ClashRun {
    id: string;
    jobId: string;
    date: string;
    clashCount: number;
}
interface ClashBase {
    /** Deterministic FNV-1a hash of the normalized pair (elementA.guid, elementB.guid). Stable across runs. */
    id: string;
    jobId: string;
    firstSeenRunId: string;
    lastSeenRunId: string;
    elementA: ClashElement;
    elementB: ClashElement;
    point: [number, number, number];
    status: ClashStatus;
    comments?: string;
}
export interface HardClash extends ClashBase {
    type: "hard";
    volume?: number;
}
export interface ClearanceClash extends ClashBase {
    type: "clearance";
    distance: number;
}
export type Clash = HardClash | ClearanceClash;
export interface MarkerGroup {
    id?: string;
    point: [number, number, number];
    count: number;
    status?: ClashStatus;
}

/** `clashes.frag`'s path relative to `__project_data/`, for consumers that
 *  persist it via `projectStorageContext` instead of talking to `client`
 *  directly (see `buildClashBuffer`). */
export declare const CLASH_DATA_PATH = "collider/clashes.frag";
export interface ExecutionEntry {
    jobId: string;
    executionId: string;
    startedAt: string;
}
/** `cachedFileId`, when given, skips folder/file resolution (3 of the 4
 *  network round-trips this normally takes) — the file's ID never changes
 *  once created, so callers that already know it (see `ClashesManager`'s
 *  `_clashFragFileId`) should always pass it. */
export declare function ensureClashFragFileId(client: PlatformClient, projectId: string, cachedFileId?: string): Promise<string>;
export declare function getExecutions(client: PlatformClient, projectId: string | undefined): Promise<ExecutionEntry[]>;
export interface ClashData {
    jobs: ClashJob[];
    runs: ClashRun[];
    clashes: Clash[];
    queries: ClashQuery[];
    matrices: ClashMatrix[];
    /** Resolved once here — callers should cache and pass back into
     *  `loadClashData`/`buildClashBuffer` as `cachedFileId` to skip
     *  re-resolving it (see `ensureClashFragFileId`). */
    fileId: string;
}
export declare function loadClashData(client: PlatformClient, projectId: string, cachedFileId?: string): Promise<ClashData>;
/**
 * Diffs `data` against the persisted `clashes.frag` and builds the updated
 * buffer, WITHOUT uploading it — callers decide how/where to persist the
 * result (direct `client.updateFile`, via `projectStorageContext`, etc).
 * Still reads the current file via `client` to diff against (job/id
 * reconciliation needs the previous state), same as `saveClashData` always did.
 */
export declare function buildClashBuffer(client: PlatformClient, projectId: string, data: {
    queries: ClashQuery[];
    matrices: ClashMatrix[];
    jobs: ClashJob[];
    clashes: Clash[];
}, onJobsReconciled: (toAdd: ClashJob[], toRemove: Set<string>) => void, cachedFileId?: string): Promise<{
    blob: Blob;
    fileId: string;
}>;
/** Default persistence path: builds the buffer and uploads it straight to
 *  `client`. Kept as the manager's out-of-the-box behavior for any consumer
 *  that never overrides `ClashesManager.save` (e.g. doesn't route through
 *  `projectStorageContext`). */
export declare function saveClashData(client: PlatformClient, projectId: string, data: {
    queries: ClashQuery[];
    matrices: ClashMatrix[];
    jobs: ClashJob[];
    clashes: Clash[];
}, onJobsReconciled: (toAdd: ClashJob[], toRemove: Set<string>) => void): Promise<void>;


declare class _ClashesManager extends OBC.Component {
    static readonly uuid: "2c9f4e8d-3a1b-4c5e-9d7f-0a2b6c8e1d3f";
    enabled: boolean;
    readonly onQueriesChanged: OBC.Event<ClashQuery[]>;
    readonly onMatricesChanged: OBC.Event<ClashMatrix[]>;
    readonly onJobsChanged: OBC.Event<ClashJob[]>;
    readonly onRunsChanged: OBC.Event<ClashRun[]>;
    readonly onClashesChanged: OBC.Event<Clash[]>;
    readonly onClashStatusChanged: OBC.Event<Clash[]>;
    /** Dispara cuando empieza el debounce de guardado (pendiente de persistir). */
    readonly onSaveStart: OBC.Event<void>;
    /** Dispara al terminar el guardado. true = éxito, false = error. */
    readonly onSaveComplete: OBC.Event<boolean>;
    world?: OBC.World;
    /** Suprimir auto-save durante carga de datos (usar loadingData = true antes, false después). */
    loadingData: boolean;
    /** Registrar desde la app host para recargar datos desde el storage al terminar una ejecución. */
    reload?: () => Promise<void>;
    /** Registrar desde la app host para consultar qué jobIds tienen ejecución activa en storage. */
    checkExecutions?: () => Promise<Set<string>>;
    /** Registrar desde la app host para persistir queries y matrices al storage del proyecto. */
    save?: () => Promise<void>;
    /** Jobs con una ejecución cloud activa. Poblado por la app host al arrancar. */
    readonly runningJobIds: Set<string>;
    /** Mapa jobId → executionId para reconectar al WebSocket. Poblado por la app host al arrancar. */
    readonly activeExecutions: Map<string, string>;
    readonly onRunningJobsChanged: OBC.Event<Set<string>>;
    readonly onRunProgress: OBC.Event<{
        message: string;
        progress: number;
    }>;
    readonly onRunComplete: OBC.Event<{
        runId: string;
        clashCount: number;
    }>;
    readonly onRunError: OBC.Event<{
        code?: string;
        message: string;
    }>;
    readonly onReloadingChanged: OBC.Event<boolean>;
    isReloading: boolean;
    /** True once init(client) has been called — safe to call run(). */
    get ready(): boolean;
    private _client?;
    private _projectId?;
    /** `clashes.frag`'s file ID, resolved once by `init()`/`reload()`'s
     *  `loadClashData` call. Never changes once the file exists — passing it
     *  into `buildClashBuffer` skips 3 of its 4 network round-trips. */
    private _clashFragFileId?;
    private _reconnectingJobIds;
    private _queries;
    private _matrices;
    private _saveTimer?;
    private _savePromise?;
    private _jobs;
    private _runs;
    private _clashes;
    private _markers;
    private static _geo;
    get queries(): ClashQuery[];
    set queries(value: ClashQuery[]);
    get matrices(): ClashMatrix[];
    set matrices(value: ClashMatrix[]);
    private _scheduleSave;
    /** Chains onto any save already in flight instead of firing a second,
     *  concurrent `_doSave()` — two overlapping calls would race on
     *  `buildClashBuffer`'s read-diff-reconcile cycle (real network I/O;
     *  `onJobsReconciled` mutating `this.jobs` from two stale reads at once)
     *  and on the upload itself. It also keeps `flush()` correct: it just
     *  awaits `_savePromise`, so if that got overwritten by a newer, unrelated
     *  save instead of chained, flush() could resolve while an earlier save
     *  was still genuinely in flight. */
    private _queueSave;
    private _doSave;
    /** Cancela el debounce pendiente y ejecuta el save inmediatamente. Espera a que complete. */
    flush(): Promise<void>;
    /**
     * Builds the current `clashes.frag` buffer (diffed/reconciled against what's
     * persisted) WITHOUT uploading it. For consumers (e.g. `clashes-panel`) that
     * override `save` to persist via `projectStorageContext` instead of the
     * default direct-`client` path.
     */
    buildClashBuffer(): Promise<Blob>;
    get jobs(): ClashJob[];
    set jobs(value: ClashJob[]);
    get runs(): ClashRun[];
    set runs(value: ClashRun[]);
    get clashes(): Clash[];
    set clashes(value: Clash[]);
    queryById(id: string): ClashQuery | undefined;
    private _clashStylesRegistered;
    /** Green — elementA's highlight color. Public so consumers (e.g. "create
     *  topic from clash") can build a matching BCF viewpoint `componentColors`
     *  entry without duplicating the hex value. */
    readonly STYLE_A = "#22c55e";
    /** Red — elementB's highlight color. Same reasoning as `STYLE_A`. */
    readonly STYLE_B = "#ef4444";
    private _clashStyle;
    highlightAllClashes(clashes: Clash[]): void;
    ghostClashes(clashes: Clash[]): Promise<void>;
    ghostClash(clash: Clash): Promise<void>;
    clearGhostClash(): Promise<void>;
    highlightClash(clash: Clash): void;
    clearClashHighlight(): void;
    showMarkers(groups: MarkerGroup[]): void;
    hideMarkers(): void;
    toViewerPoint(point: [number, number, number]): THREE.Vector3;
    private _toViewer;
    private _renderMarkers;
    private _clearMarkers;
    cluster(clashes: Clash[], threshold: number): Clash[][];
    private _setHighlighterEnabled;
    private _isolatedMaterials;
    runsForJob(jobId: string): ClashRun[];
    clashesForRun(runId: string): Clash[];
    updateClash(id: string, changes: {
        status?: ClashStatus;
        comments?: string;
    }): void;
    /**
     * Initializes the manager from cloud storage: loads clash data, wires save/reload,
     * reads in-flight executions, and resolves the viewer world (non-blocking).
     * Consumer apps call this once instead of wiring all the pieces manually.
     */
    init(client: PlatformClient): Promise<void>;
    /** Launches clash detection in a Web Worker. Fires onRunProgress/onRunComplete/onRunError. */
    run(jobId: string): void;
    private _handleWorkerComplete;
    /** Reconnects to an in-flight execution when the user opens a job that was running before page load. */
    reconnectIfRunning(jobId: string): void;
    private _listenToExecution;
    private _firstWorld;
}

export type ClashesManager = InstanceType<typeof _ClashesManager>;
export const ClashesManager = { uuid: '2c9f4e8d-3a1b-4c5e-9d7f-0a2b6c8e1d3f' } as typeof _ClashesManager & { uuid: '2c9f4e8d-3a1b-4c5e-9d7f-0a2b6c8e1d3f' };

/**
 * Which action buttons to expose per file row. All default to `true`.
 */
export interface FileListActions {
    download?: boolean;
    rename?: boolean;
    delete?: boolean;
}
/**
 * Config passed to {@link FileList.create}.
 */
export interface FileListConfig {
    /** Services client used to list and mutate files. */
    client: EngineServicesClient;
    /** Optional folder ID to scope the list. If omitted, lists root files. */
    folderId?: string;
    /** Which action buttons to show per row. Defaults to all enabled. */
    actions?: FileListActions;
    /** Called when a file row is clicked (not an action button). */
    onFileClick?: (file: Item) => void;
}
/**
 * The result returned by {@link FileList.create}.
 */
export interface FileListInstance {
    /** The DOM element to mount somewhere in your layout. */
    element: HTMLElement;
    /** Reloads the list from the services client. */
    refresh: () => Promise<void>;
    /** Changes the folder scope and reloads. Pass `undefined` for the root. */
    setFolder: (folderId?: string) => Promise<void>;
    /** Removes the element and forgets the instance. */
    dispose: () => void;
}

/**
 * Built-in component that renders a file list backed by the services client,
 * with built-in download / rename / delete actions.
 *
 * The backing data comes from {@link EngineServicesClient.listFiles}, so the
 * list stays in sync with the storage service. Each call to {@link create}
 * returns an independent instance with its own DOM element.
 *
 * @example
 * ```ts
 * const fileList = components.get(FileList);
 * const { element, refresh } = fileList.create({
 *   client: app.client,
 *   folderId: someFolderId,
 * });
 * container.appendChild(element);
 * ```
 */
declare class _FileList extends OBC.Component {
    static readonly uuid: "b0b5e2a2-0b3a-4a6b-8b1c-0b1c4a6b8b1c";
    enabled: boolean;
    readonly name = "FileList";
    private _instances;
    /**
     * Creates a new file-list instance. Returns the DOM element to mount plus a
     * `refresh` handle to reload the list, a `setFolder` to change scope, and a
     * `dispose` to remove it.
     */
    create(config: FileListConfig): FileListInstance;
    /**
     * Removes every instance this manager has created.
     */
    dispose(): void;
}

/**
 * Built-in component that renders a file list backed by the services client,
 * with built-in download / rename / delete actions.
 *
 * The backing data comes from {@link EngineServicesClient.listFiles}, so the
 * list stays in sync with the storage service. Each call to {@link create}
 * returns an independent instance with its own DOM element.
 *
 * @example
 * ```ts
 * const fileList = components.get(FileList);
 * const { element, refresh } = fileList.create({
 *   client: app.client,
 *   folderId: someFolderId,
 * });
 * container.appendChild(element);
 * ```
 */
export type FileList = InstanceType<typeof _FileList>;
/**
 * Built-in component that renders a file list backed by the services client,
 * with built-in download / rename / delete actions.
 *
 * The backing data comes from {@link EngineServicesClient.listFiles}, so the
 * list stays in sync with the storage service. Each call to {@link create}
 * returns an independent instance with its own DOM element.
 *
 * @example
 * ```ts
 * const fileList = components.get(FileList);
 * const { element, refresh } = fileList.create({
 *   client: app.client,
 *   folderId: someFolderId,
 * });
 * container.appendChild(element);
 * ```
 */
export const FileList = { uuid: 'b0b5e2a2-0b3a-4a6b-8b1c-0b1c4a6b8b1c' } as typeof _FileList & { uuid: 'b0b5e2a2-0b3a-4a6b-8b1c-0b1c4a6b8b1c' };

/** One element mutation inside a revit-flow commit. */
export interface RevitFlowChange {
    /** create → element added, update → geometry/data changed, delete → removed. */
    type: "create" | "update" | "delete" | string;
    /** Revit UniqueId (GUID). Resolves to a fragments localId via getLocalIdsByGuids. */
    uniqueId: string;
}
/** Per-commit change tallies, mirrored from the add-in's `counts` block. */
export interface RevitFlowCounts {
    added: number;
    modified: number;
    removed: number;
}
/**
 * A revit-flow commit — one push of changes from the Revit add-in. `id` is a
 * monotonic integer; `parent` points at the previous commit (null for the
 * root). The first commit is the baseline: its geometry IS the visible model
 * file. Later commits carry only their delta geometry, in a HIDDEN .frag whose
 * id is `deltaId`.
 */
export interface RevitFlowCommit {
    /**
     * WHAT this commit is. Identity, minted by whoever wrote it, meaningful outside the model it
     * belongs to — which the old integer was not: that was the platform's storage version, a number
     * the CDE handed out. An application that does not push through a Revit central has no such
     * number, and an integer sequence asserts one line of history, which Revit's central enforces and
     * nothing else has to.
     */
    guid: string;
    /**
     * The commits this one was built on. Absent on a root.
     *
     * A LIST, because a history that can only ever be a line is a different thing from a graph. A
     * fork was already expressible with a single parent — two commits naming the same one — but a
     * MERGE means naming both lines, and that needs this. The first entry is the line the commit
     * continues, which is what lets the panel lay out lanes without guessing which side is the trunk.
     *
     * Revit never writes more than one: its central IS a single line and it merges inside itself
     * rather than in this graph. The list is for the applications that are not Revit.
     */
    parents?: string[] | null;
    /**
     * WHERE this landed in the CDE, when there is such a place. Data, never identity, and never shown
     * as the commit's name. Absent for any application with no version counter.
     */
    version?: number;
    /**
     * Position in this model's history, computed from the parent chain when the commits are read.
     *
     * Order questions — "is this commit before the one on screen?" — used to be asked of the integer
     * id, which meant every application had to produce a sequence to be understood. They are asked of
     * this instead: derived from the graph, so an application that has no numbers still answers them.
     */
    ordinal: number;
    /**
     * What the author said this commit was for, in their own words. Absent when nobody said
     * anything, which is most commits.
     *
     * In Revit it comes from the Comment box in its own Synchronize with Central dialog, which
     * people have been typing into for years while it went nowhere. Free text: never parsed, never
     * relied on for structure.
     */
    message?: string;
    author: string;
    source: string;
    timestamp: string;
    changes: RevitFlowChange[];
    counts: RevitFlowCounts;
    /**
     * Hidden-file id of this commit's delta .frag (created+modified geometry).
     * Absent on the baseline/first commit and on geometry-less commits. The
     * platform's hidden-file API has no queryable name, so the delta is loaded by
     * this id, never by filename.
     */
    deltaId?: string;
    /**
     * Platform user id of the committer, recorded by the add-in from its API key. Lets the
     * UI resolve the author to a real project member (avatar + name) via getProjectData,
     * instead of deriving initials from the raw Revit username. Absent on history written
     * before this was recorded, or when the key isn't a readable JWT.
     */
    userId?: string;
    /**
     * Which loaded model this commit belongs to (the model file's id == the viewer's
     * modelId). Tagged in by the manager when it reads the history: commit ids are
     * per-model version numbers, so they repeat across models and can't identify a commit
     * on their own.
     */
    modelId?: string;
    /** The model's name AS SHOWN IN PROJECT FILES, for the cards and the model filter. */
    modelName?: string;
    /**
     * This commit re-exported the WHOLE model, so the project's visible .frag shows the
     * model as of here — what anyone opening it from Project Files gets, without the
     * history panel. True for the initial capture and for the periodic full exports the
     * team publishes; ordinary commits ship only their delta.
     */
    full?: boolean;
    /**
     * Interoperability operations this commit materialised. Present only when somebody in
     * Revit pulled a deferred edit: the commit is the native half of it, and this is the
     * link back to the operation that asked for it. Ordinary hand-authored commits, which
     * are nearly all of them, carry no such key at all.
     */
    appliedOps?: string[];
    /**
     * Set when this entry is NOT a commit but a deferred edit still waiting to be applied.
     *
     * Pending operations are surfaced commit-SHAPED rather than as a parallel kind of thing, so
     * they inherit search, the user and model filters, the change-kind chips and the
     * filter-by-selection behaviour instead of needing all of it reimplemented. It also means
     * one of them can be clicked and previewed: a `modify` or `delete` names elements that
     * already exist, which is exactly what the outline machinery consumes, so you can see what
     * a change will touch before anybody applies it. A `create` has nothing to show yet, which
     * is honest rather than missing.
     *
     * Everything that treats an entry as history must check this first: it has not happened.
     */
    pendingOp?: RevitFlowOp;
}
/** Shape of `revitflow_history.json`. */
export interface RevitFlowHistory {
    model: string;
    commits: RevitFlowCommit[];
}
/**
 * One deferred edit waiting to be applied to a model.
 *
 * Operations are NOT commits and do not live in the graph: a commit is immutable past, an
 * operation is optional future. They sit above the model's HEAD until somebody opens the
 * model in Revit and applies one, at which point they become a commit and stop being
 * pending. Mirrors the add-in's `revitflow_ops.json`.
 */
export interface RevitFlowOp {
    opId: string;
    /** Groups the operations one authored action produced across several models. */
    batchId?: string;
    /** Hidden-file id of the operation's .frag payload. */
    fragId?: string;
    title?: string;
    /** add | set | remove | mixed. Older queues say modify | create | delete. */
    verb?: string;
    author?: string;
    /**
     * Platform user id of whoever authored it. Resolved to a real project member exactly as a
     * commit's is, so the same person does not appear as "Antonio That Open" on their commits
     * and as their raw OS username on their operations.
     */
    userId?: string;
    createdAt?: string;
    /** The commit this operation was authored against. */
    /** The commit this was authored against, by guid. What a proposal actually refers to. */
    baseCommitGuid?: string;
    /** The platform version that commit landed in. Data, for reconciling with the CDE. */
    baseCommit?: number;
    /** How many elements it targets. */
    targets?: number;
    state?: "pending" | "applied" | "discarded" | string;
    /** The native commit that materialised it, once applied. */
    appliedInCommit?: number | null;
    /**
     * Native ids the operation actually touched or created, written by the add-in when it applied.
     * A FLAT list: it does not say which source object produced which result, because nothing in
     * this system ties an element to an element in another application.
     *
     * It is what lets an APPLIED proposal be selected and previewed like a commit, with no payload
     * fetch at all. Note which halves that leaves blind, because they are opposite ends:
     *
     *   add     pending → nothing exists yet   ·  applied → these are what it made
     *   set     pending → its targets          ·  applied → the same targets
     *   remove  pending → its targets          ·  applied → nothing, they are gone
     *
     * So the only case still needing the payload is a PENDING set or remove, whose target ids live
     * in the operation's .frag rather than in this index.
     */
    affectedIds?: string[];
    /** Tagged in by the manager, exactly as commits are: which model this queue belongs to. */
    modelId?: string;
    modelName?: string;
}
/** Shape of `revitflow_ops.json`. */
export interface RevitFlowOpsIndex {
    schema?: string;
    ops: RevitFlowOp[];
}
/** Dominant change type of a commit, used to color its timeline node. */
export type DominantChange = "create" | "update" | "delete";

/** What to do with elements outside the selected commit. */
export type ContextMode = "default" | "hidden";
/** The three kinds of change a commit can carry. */
export type ChangeKind = "create" | "update" | "delete";
/**
 * Stable id for a commit across models — which is now just its guid.
 *
 * It used to have to be `${model}:${id}`, because the id was a per-model version number and every
 * model had a commit 3. A guid needs no help being unique, and that is exactly what it was for.
 */
export declare const commitKey: (c: {
    guid?: string;
    pendingOp?: {
        opId: string;
    };
}) => string;
/** How the commit is shown in 3D: review colours, or the model as it ended up. */
export type HighlightMode = "colored" | "plain";
/** Dominant change type of a commit: delete → create → update. */
export declare function dominantChange(commit: RevitFlowCommit): DominantChange;
/**
 * GitHistoryManager — headless engine for the revit-flow git-history built-in.
 *
 * Owns ALL viewer mutation for the change outlines. It does NOT load the model —
 * the user opens a model from the Project Files panel, and this manager reacts to
 * that load: it reads the model's hidden `revitflow_history.json` (if any) and
 * publishes the commit list. Showing a commit outlines its changed elements
 * (create → green, update → blue, delete → red) via three independently-colored
 * `OBF.Outliner` groups — a cheap post-process outline that never recolors the
 * fragment geometry. The Lit panel (`top-git-history`) is intent-only: it calls
 * these methods and subscribes to the events below.
 *
 * Data model, per loaded model (fileId == modelId), all HIDDEN children of it:
 *   - revitflow_history.json — { model, commits: [{ id, parent, author, source,
 *       timestamp, changes:[{type,uniqueId}], counts }] }. The first commit is the
 *       INITIAL full-model capture (its geometry == the visible baseline file).
 *   - revitflow_frag_<N>.frag — delta fragments for commit N (its created+modified
 *       geometry), loaded on demand so created elements can be colored.
 */
declare class _GitHistoryManager extends OBC.Component {
    static readonly uuid: "3f9c1a7e-6b2d-4e18-9a5c-7d0e2f4b6c81";
    enabled: boolean;
    readonly onCommitsChanged: OBC.Event<RevitFlowCommit[]>;
    /** {@link commitKey} of the highlighted commit, or null when cleared. */
    readonly onCommitChanged: OBC.Event<string | null>;
    readonly onLoadingChanged: OBC.Event<boolean>;
    readonly onError: OBC.Event<string>;
    /** The GUID currently selected in the 3D view (null when the selection is cleared). */
    readonly onSelectedGuidChanged: OBC.Event<string | null>;
    /** A source icon was added or replaced. */
    readonly onSourceIconsChanged: OBC.Event<void>;
    /**
     * Which mark to draw on a commit, by the application that wrote it.
     *
     * Every commit already says who made it, in `source`. The panel used to draw the Revit logo on
     * all of them regardless, which was true while Revit was the only thing that could write one and
     * became a lie the moment anything else did: a commit from another tool would claim to be a
     * Revit commit, on the one part of the row whose whole job is to say where a change came from.
     *
     * The format is deliberately open about who writes history, so the icons have to be too. This is
     * the registry. Only `revit` is built in; an application adds its own:
     *
     *   const history = components.get(GitHistoryManager);
     *   history.setSourceIcon("rhino", "https://…/rhino.svg");   // a URL, or a data: URI
     *   history.setSourceIcon("tekla", "<svg viewBox='0 0 24 24'>…</svg>");   // or the markup
     *
     * A source with no icon gets a neutral one rather than somebody else's.
     */
    readonly sourceIcons: Map<string, string>;
    /**
     * @param source the commit's own `source` value, matched case-insensitively.
     * @param icon a URL, a `data:` URI, or inline `<svg>` markup.
     */
    setSourceIcon(source: string, icon: string): void;
    world?: OBC.World;
    /**
     * What happens to elements that are NOT part of the selected commit:
     *   "default" — left as they are (the change outlines sit on the full model)
     *   "hidden"  — hidden entirely, isolating the commit's elements
     *
     * A dimmed ("ghost") middle ground was dropped: the fragments x-ray writes depth
     * from the pixels its screen door keeps, so dimmed geometry still occluded the very
     * elements under review — worse the denser the model in front. Fixing that properly
     * belongs in the renderer, not here, so this offers the two states that are exact.
     */
    contextMode: ContextMode;
    /**
     * Which change kinds to outline. All three by default; the panel's filter buttons
     * narrow it (e.g. only deletions) without reloading anything.
     */
    typeFilter: Set<ChangeKind>;
    /**
     * How many commits either side of the selected one to keep pre-loaded, so stepping
     * through the timeline is instant instead of fetching on every click. The window
     * slides with the selection and everything outside it is disposed, which bounds
     * memory no matter how long the history gets.
     */
    prefetchRadius: number;
    /**
     * How a commit is presented in 3D:
     *   "colored" — outline created/edited/deleted in their colours (the review lens)
     *   "plain"   — no outlines: the model simply as it stood AFTER the commit, so the
     *               deleted elements are hidden rather than painted red
     */
    highlightMode: HighlightMode;
    /** @deprecated kept so older callers still compile — maps onto contextMode. */
    get isolateChanges(): boolean;
    /** Green — created elements. */
    readonly COLOR_CREATED = "#22c55e";
    /** Golden yellow — modified elements. */
    readonly COLOR_MODIFIED = "#e3b341";
    /** Red — deleted elements. */
    readonly COLOR_DELETED = "#ef4444";
    readonly GROUP_CREATED = "revitflow-created";
    readonly GROUP_MODIFIED = "revitflow-modified";
    readonly GROUP_DELETED = "revitflow-deleted";
    private _client?;
    private _projectId?;
    /**
     * One entry per loaded revit-flow model. Commit ids are per-model version numbers, so
     * they collide across models — every commit is tagged with its modelId and a commit is
     * addressed by {@link commitKey}, never by id alone.
     */
    private _models;
    /** Which models the timeline shows. Empty = all of them. */
    private _selectedModels;
    /** `${modelId}:${id}` of the commit currently highlighted, or null. */
    private _currentKey;
    /** modelIds already probed for a sibling history (avoids re-probing). */
    private _probed;
    /** hiddenIds of delta frags this manager has loaded into the viewer. */
    private _loadedDeltas;
    /** Ghosted localIds per modelId, so isolate can be cleared/re-applied. */
    private _contextApplied;
    /** localIds hidden because the shown commit deleted them (plain mode). */
    private _hiddenDeleted;
    /** localIds hidden because a newer visible source supplies the same element. */
    private _hiddenSuperseded;
    /** True once the three named Outliner groups have been created. */
    private _groupsReady;
    private _loading;
    private _wired;
    constructor(components: OBC.Components);
    get ready(): boolean;
    get loading(): boolean;
    /**
     * Commits of the selected models, newest last, interleaved by time so a multi-model
     * timeline reads chronologically rather than model-by-model.
     */
    get commits(): RevitFlowCommit[];
    /** True when this entry is a proposal rather than something that happened. */
    isProposal(commit: RevitFlowCommit | null | undefined): boolean;
    /**
     * The entry a proposal/commit links to, in whichever direction applies: a commit points at
     * the proposal it materialised, a proposal at the commit that did it. Returns null when
     * there is no counterpart, which is the normal case for hand-authored work.
     */
    counterpart(commit: RevitFlowCommit): RevitFlowCommit | null;
    /**
     * Deferred edits still waiting to be applied, across the selected models, oldest first.
     *
     * Kept separate from {@link commits} on purpose. A commit is something that happened; a
     * pending operation is something that might. Merging them into one list would force every
     * consumer to keep asking which kind it was holding.
     */
    get pendingOps(): RevitFlowOp[];
    /** The loaded revit-flow models, for the panel's model filter. */
    get models(): Array<{
        modelId: string;
        name: string;
        commits: number;
    }>;
    get selectedModels(): Set<string>;
    get currentKey(): string | null;
    /** Name of the single loaded model, or "" when there are none/several. */
    get modelName(): string;
    /** The commit behind {@link currentKey}, or undefined when nothing is highlighted. */
    private _currentCommit;
    /** Restrict the timeline to these models (empty set = show all of them). */
    setSelectedModels(modelIds: Iterable<string>): Promise<void>;
    /** True when `commit` is its model's baseline (the full-model capture). */
    isBaseline(commit: RevitFlowCommit): boolean;
    /** True if `commit` has a hidden delta .frag to load. */
    hasFrag(commit: RevitFlowCommit): boolean;
    /**
     * Wire the platform client and subscribe to model loads. Does NOT load any
     * geometry: the manager only attaches to models the user opens from the Files
     * panel. Consumer panels call this once on connect.
     */
    init(client: PlatformClient): Promise<void>;
    /**
     * Follow the viewer's selection so the element view tracks whatever the user clicks in
     * 3D — no "trace this" button to press. The Highlighter's events appear asynchronously
     * (they're registered when the viewer sets it up), so retry briefly until they exist.
     */
    private _watchSelection;
    private _onModelSet;
    private _onModelDeleted;
    /**
     * Probe a loaded model for a sibling visible `revitflow_history.json` in its
     * folder. If present, adopt it as the active model and publish its commits.
     * Silent for non-revit models and for our own delta frags — only genuine
     * fetch/parse failures raise onError.
     */
    private _probeModel;
    /**
     * Read the model's deferred-edit queue, if it has one.
     *
     * Best effort by design: a model that has never been the target of an operation simply has
     * no queue, and that is the normal case rather than an error. A failure here must never
     * cost the user their history, which is why it cannot throw out of the probe.
     */
    private _readOps;
    /**
     * Re-scan every currently-loaded model for a hidden revit-flow history (the
     * panel's Refresh button). Clears the probe cache so models load-order edge
     * cases re-resolve.
     */
    loadHistory(): Promise<void>;
    /**
     * Show `commit`. The baseline geometry is the visible model the user already loaded, so
     * the baseline view just clears outlines. Any other commit pulls its hidden delta frag
     * in (so created elements exist) and outlines its changed elements. Fires
     * onCommitChanged. Takes the commit itself, not an id: ids repeat across models.
     */
    showCommit(commit: RevitFlowCommit): Promise<void>;
    /**
     * Keep the deltas of the commits around `centerId` loaded and drop the rest, so
     * stepping through the timeline never stalls and memory stays bounded: moving from
     * commit 10 to 11 fetches one delta and disposes one, instead of reloading a window.
     */
    private _slidePrefetchWindow;
    /**
     * Show the model as it stood AT `commit`: the visible baseline is the model at its
     * INITIAL commit, and everything created later lives in per-commit delta .frags loaded
     * as separate models. Those deltas stay loaded (the prefetch window keeps neighbours
     * warm), so stepping BACK has to hide the ones from later commits — otherwise a wall
     * added in commit 3 was still sitting there while you were looking at commit 2.
     * Only touches deltas of the commit's own model; other models keep their own state.
     */
    private _applyFutureVisibility;
    /** Which commit a loaded delta belongs to (deltas are keyed by their hidden id). */
    private _commitOfDelta;
    /** Make every loaded delta visible again (the model as of its latest commit). */
    private _showAllDeltas;
    /** Remove all revit-flow outlines + ghosting and reset the selection. */
    clear(): Promise<void>;
    /** Set what happens to non-commit elements; re-applies to the current commit. */
    setContextMode(mode: ContextMode): Promise<void>;
    /**
     * Every commit that touched `uniqueId`, oldest first, with what happened to it there.
     * The element's life story: created here, edited there, finally deleted.
     */
    elementHistory(uniqueId: string): Array<{
        commit: RevitFlowCommit;
        type: string;
    }>;
    /** Per-author totals across the (optionally date-filtered) history. */
    userActivity(since?: Date): Array<{
        author: string;
        userId?: string;
        commits: number;
        added: number;
        modified: number;
        removed: number;
        last: string;
    }>;
    /**
     * The GUID of whatever is currently selected in the viewer, so the element view can
     * follow the user's selection. Returns null when nothing (or something unresolvable)
     * is selected.
     */
    /** GUIDs of everything currently selected in the viewer (empty when nothing is). */
    selectedGuids(): Promise<string[]>;
    selectedGuid(): Promise<string | null>;
    /**
     * Select every element the commit touched, in the viewer's own selection — so the
     * usual tools (properties, isolate, zoom) work on it like any hand-made selection.
     * Honours the current type filter, so "only deletions" selects only those.
     * @returns how many elements ended up selected.
     */
    selectCommitElements(commit: RevitFlowCommit, zoom?: boolean): Promise<number>;
    /** Show/hide one kind of change; re-applies to the current commit. */
    setTypeVisible(kind: ChangeKind, on: boolean): Promise<void>;
    /** @deprecated use setContextMode. */
    setIsolateChanges(on: boolean): Promise<void>;
    /** The shared Outliner component (created on first access by the viewer). */
    private _outliner;
    /**
     * Create the three independently-colored outline groups once. The viewer
     * owns the Outliner's DEFAULT group (selection) — we only add our own named
     * groups and never touch "default".
     */
    private _ensureGroups;
    /** Clear our three outline groups only — leaves the viewer's default group. */
    private _clearOutlines;
    /**
     * Resolve each change bucket's GUIDs to localIds across every loaded model
     * and route them to the matching outline group.
     */
    private _outlineCommit;
    /**
     * Remove every localId that `_applySupersededVisibility` has hidden from a change map.
     * Returns a copy: the input maps come from `_buildMap` and are used elsewhere.
     */
    private _dropSuperseded;
    /**
     * Hide (or restore) the elements a commit deleted. Tracked separately from the context
     * modes so switching Colored↔Plain doesn't disturb ghosting or the rest of the model.
     */
    private _applyDeletedVisibility;
    /**
     * Show each element ONCE: from the newest source that supplies it.
     *
     * THE BUG THIS EXISTS FOR. The baseline .frag holds the whole model as of the first
     * commit, and every later commit ships a delta .frag with the geometry it created AND
     * the geometry it modified. Both stay in the scene. For a CREATED element that is
     * right — it exists in exactly one place. For a MODIFIED one it is not: the element is
     * in the baseline at its old shape and in the delta at its new one, and the viewer drew
     * both. Measured 2026-08-05 on a wall whose height Quim raised: the new wall stood
     * proud of the old one, with the coincident faces z-fighting into a dotted band.
     *
     * The rule is the obvious one once stated: for any element, only the newest VISIBLE
     * source may draw it. Deltas are walked newest-first, each guid is claimed by the first
     * source that has it, and every older copy — in an older delta or in the baseline — is
     * hidden. Deltas newer than the commit being shown are already hidden wholesale by
     * `_applyFutureVisibility`, so they never get to claim anything.
     *
     * Restores before it hides, like `_applyDeletedVisibility`, so stepping backwards
     * through the timeline brings the old geometry back rather than accumulating hidden
     * elements until the model is empty.
     */
    private _applySupersededVisibility;
    /** Switch between review colours and the plain post-commit model. */
    setHighlightMode(mode: HighlightMode): Promise<void>;
    /**
     * Make sure the geometry of `deleted` GUIDs is loaded. Anything already resolvable in
     * a loaded model (the usual case: the element shipped in the baseline) needs nothing;
     * for the rest, walk back through the history to the commit that CREATED each one and
     * load that commit's delta, which is the last place its geometry existed.
     */
    private _ensureDeletedGeometry;
    /** GUIDs → { modelId: Set<localId> } across the given models. */
    private _buildMap;
    private _mergeMaps;
    /**
     * Dim ("ghost") or hide every element that is NOT part of the shown commit, per the
     * chosen context mode. Best-effort per model: a model that doesn't support the call is
     * simply left alone — the outlines still convey the change.
     */
    private _applyContext;
    /** Undo whatever the context mode did: drop the ghost overlay and restore visibility. */
    private _clearContext;
    /**
     * Kept for the panel's connect hook. Prefetching is now driven by the SELECTION (see
     * _slidePrefetchWindow): nothing is downloaded until a commit is opened, and only its
     * neighbourhood is kept. Warming the newest N up front, as this used to do, spent
     * bandwidth on commits nobody had asked for and grew without bound.
     */
    warmDeltas(): void;
    /** Load a commit's hidden delta .frag (by its hidden id) into the viewer (modelId == hiddenId). */
    private _ensureDeltaLoaded;
    private _setLoading;
    private _firstWorld;
}

/**
 * GitHistoryManager — headless engine for the revit-flow git-history built-in.
 *
 * Owns ALL viewer mutation for the change outlines. It does NOT load the model —
 * the user opens a model from the Project Files panel, and this manager reacts to
 * that load: it reads the model's hidden `revitflow_history.json` (if any) and
 * publishes the commit list. Showing a commit outlines its changed elements
 * (create → green, update → blue, delete → red) via three independently-colored
 * `OBF.Outliner` groups — a cheap post-process outline that never recolors the
 * fragment geometry. The Lit panel (`top-git-history`) is intent-only: it calls
 * these methods and subscribes to the events below.
 *
 * Data model, per loaded model (fileId == modelId), all HIDDEN children of it:
 *   - revitflow_history.json — { model, commits: [{ id, parent, author, source,
 *       timestamp, changes:[{type,uniqueId}], counts }] }. The first commit is the
 *       INITIAL full-model capture (its geometry == the visible baseline file).
 *   - revitflow_frag_<N>.frag — delta fragments for commit N (its created+modified
 *       geometry), loaded on demand so created elements can be colored.
 */
export type GitHistoryManager = InstanceType<typeof _GitHistoryManager>;
/**
 * GitHistoryManager — headless engine for the revit-flow git-history built-in.
 *
 * Owns ALL viewer mutation for the change outlines. It does NOT load the model —
 * the user opens a model from the Project Files panel, and this manager reacts to
 * that load: it reads the model's hidden `revitflow_history.json` (if any) and
 * publishes the commit list. Showing a commit outlines its changed elements
 * (create → green, update → blue, delete → red) via three independently-colored
 * `OBF.Outliner` groups — a cheap post-process outline that never recolors the
 * fragment geometry. The Lit panel (`top-git-history`) is intent-only: it calls
 * these methods and subscribes to the events below.
 *
 * Data model, per loaded model (fileId == modelId), all HIDDEN children of it:
 *   - revitflow_history.json — { model, commits: [{ id, parent, author, source,
 *       timestamp, changes:[{type,uniqueId}], counts }] }. The first commit is the
 *       INITIAL full-model capture (its geometry == the visible baseline file).
 *   - revitflow_frag_<N>.frag — delta fragments for commit N (its created+modified
 *       geometry), loaded on demand so created elements can be colored.
 */
export const GitHistoryManager = { uuid: '3f9c1a7e-6b2d-4e18-9a5c-7d0e2f4b6c81' } as typeof _GitHistoryManager & { uuid: '3f9c1a7e-6b2d-4e18-9a5c-7d0e2f4b6c81' };

/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
declare class _HelloWorld extends OBC.Component {
    static readonly uuid: "2c4ae432-fc24-43e9-9783-0c960c674e96";
    enabled: boolean;
    readonly name = "HelloWorld";
    constructor(components: OBC.Components);
    /**
     * Returns a greeting message and logs it to the console.
     * @param who - The name to greet. Defaults to `"World"`.
     */
    greet(who?: string): string;
}
/**
 * PlatformComponents.import() expects a `main` variable in scope with
 * a `componentDefinition` property pointing to the OBC.Component class.
 * The IIFE build (name: 'main') assigns this to `var main = ...`.
 */

/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
export type HelloWorld = InstanceType<typeof _HelloWorld>;
/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
export const HelloWorld = { uuid: '2c4ae432-fc24-43e9-9783-0c960c674e96' } as typeof _HelloWorld & { uuid: '2c4ae432-fc24-43e9-9783-0c960c674e96' };

/** `main.bcf`'s path relative to `__project_data/` — shared with
 *  `requestBcfSave` (`UIManager/src/utils/bcf-storage.ts`) so both sides of
 *  the save/load round-trip agree on where the file lives. */
export declare const BCF_DATA_PATH = "topics/main.bcf";
/** Downloads `__project_data/topics/main.bcf` and loads it into `BCFTopics`,
 *  if it already has content. A freshly-created file is empty (0 bytes) —
 *  not a valid BCF zip — so there's nothing to load yet in that case. */
export declare function loadBcfTopics(client: PlatformClient, projectId: string, components: OBC.Components): Promise<void>;


/**
 * Wires up everything `top-topics-panel` (and `clashes-panel`'s "create
 * topic from clash" feature) needs to work out of the box: `BCFTopics`
 * configuration (version, author, assignable users — all from real project
 * data), loading whatever BCF was previously saved for this project, and
 * resolving `Viewpoints.world` — including backfilling it onto viewpoints
 * restored from a saved BCF before the 3D world existed yet (`top-viewer`
 * only creates its `World` once `top-app` finishes mounting, which is later
 * than `init()` typically runs).
 */
declare class _TopicsManager extends OBC.Component {
    static readonly uuid: "69af63aa-19ba-4fc7-b17b-75647bac1d76";
    enabled: boolean;
    /**
     * Consumer apps call this once — same pattern as `ClashesManager.init(client)`
     * — instead of wiring `BCFTopics.setup()`, loading the saved BCF, and
     * backfilling viewpoint worlds by hand.
     */
    init(client: PlatformClient): Promise<void>;
    private _firstWorld;
}

/**
 * Wires up everything `top-topics-panel` (and `clashes-panel`'s "create
 * topic from clash" feature) needs to work out of the box: `BCFTopics`
 * configuration (version, author, assignable users — all from real project
 * data), loading whatever BCF was previously saved for this project, and
 * resolving `Viewpoints.world` — including backfilling it onto viewpoints
 * restored from a saved BCF before the 3D world existed yet (`top-viewer`
 * only creates its `World` once `top-app` finishes mounting, which is later
 * than `init()` typically runs).
 */
export type TopicsManager = InstanceType<typeof _TopicsManager>;
/**
 * Wires up everything `top-topics-panel` (and `clashes-panel`'s "create
 * topic from clash" feature) needs to work out of the box: `BCFTopics`
 * configuration (version, author, assignable users — all from real project
 * data), loading whatever BCF was previously saved for this project, and
 * resolving `Viewpoints.world` — including backfilling it onto viewpoints
 * restored from a saved BCF before the 3D world existed yet (`top-viewer`
 * only creates its `World` once `top-app` finishes mounting, which is later
 * than `init()` typically runs).
 */
export const TopicsManager = { uuid: '69af63aa-19ba-4fc7-b17b-75647bac1d76' } as typeof _TopicsManager & { uuid: '69af63aa-19ba-4fc7-b17b-75647bac1d76' };

declare class _UIManager extends OBC.Component {
    #private;
    static readonly uuid: "234f1416-528d-452a-9cc9-a16c5239b2eb";
    enabled: boolean;
    readonly name = "UIManager";
    init(): void;
}

export type UIManager = InstanceType<typeof _UIManager>;
export const UIManager = { uuid: '234f1416-528d-452a-9cc9-a16c5239b2eb' } as typeof _UIManager & { uuid: '234f1416-528d-452a-9cc9-a16c5239b2eb' };
