/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars */
/**
 * Built-in component types and runtime stubs.
 * Auto-generated by platform_builtin-components/scripts/distribute-types.mjs
 */

import type * as OBC from '@thatopen/components';
import type * as THREE from 'three';
import type { EngineServicesClient, Item, ItemFolder, ItemVersion, PlatformClient } from '../';

export interface CDEContext {
    client: PlatformClient;
    projectId: string;
}
export interface CDEUserPermissions {
    canRead: boolean;
    canCreate: boolean;
    canUpdate: boolean;
    canDelete: boolean;
    canManage: boolean;
}
export type CDEMetadataValue = string | number | boolean | null;
export interface CDENamingSegment {
    key: string;
    config?: {
        transform: (value: CDEMetadataValue) => string;
    };
}
export interface CDENamingSchema {
    separator: string;
    segments: CDENamingSegment[];
}
export interface CDEFile extends Omit<Item, 'creatingUser'> {
    createdBy: string;
    metadata: Record<string, CDEMetadataValue>;
    versions?: ItemVersion[];
    /** Tag of the file's current version (set by CDEManager from the loaded version). */
    versionTag?: string;
}
export interface CDEMetadataField {
    type: "string" | "number" | "boolean" | "list";
    description?: string;
    required?: boolean;
    label: string;
    icon?: string;
    options?: {
        value: string | number | boolean;
        label: string;
    }[];
}
export type CDEMetadataSchema = Record<string, CDEMetadataField>;
export interface CDEFileActivity {
    user: string;
    action: string;
    timestamp: string;
}
export interface CDEFileHistoryEntry {
    fileId: string;
    activity: CDEFileActivity[];
}
export interface CDEMetadataView {
    id: string;
    name: string;
    fields: string[];
}
export type CDEPendingMetadata = Record<string, CDEMetadataValue>;
export type CDEPendingMetadataSchemaEdits = Record<string, CDEMetadataField | null>;
export type FolderPendingChange = {
    kind: "create";
    tempId: string;
    name: string;
    parentId: string | null;
} | {
    kind: "rename";
    folderId: string;
    name: string;
} | {
    kind: "archive";
    folderId: string;
};
export type FolderPendingChanges = FolderPendingChange[];
export type CDEViewFileStatus = "loading" | "ready" | "failed" | "cancelled";
export type CDEMachineState = {
    kind: "idle";
} | {
    kind: "loading";
} | {
    kind: "preparing";
    files: CDEFile[];
} | {
    kind: "selected";
    files: CDEFile[];
} | {
    kind: "viewing";
    files: CDEFile[];
    fileStatus: Record<string, CDEViewFileStatus>;
    selectedFiles?: CDEFile[];
} | {
    kind: "editing";
    files: CDEFile[];
    pendingMetadata: CDEPendingMetadata;
} | {
    kind: "saving";
    files: CDEFile[];
    pendingMetadata: CDEPendingMetadata;
} | {
    kind: "deleting";
    files: CDEFile[];
} | {
    kind: "configuringMetadataSchema";
    pendingEdits: CDEPendingMetadataSchemaEdits;
} | {
    kind: "savingMetadataSchema";
    pendingEdits: CDEPendingMetadataSchemaEdits;
} | {
    kind: "configuringMetadataViews";
    pendingViews: CDEMetadataView[];
} | {
    kind: "savingMetadataViews";
    pendingViews: CDEMetadataView[];
} | {
    kind: "dragging";
    files: CDEFile[];
    sourceFolderId: string | null;
    previousState: CDEMachineState;
} | {
    kind: "movingFiles";
    files: CDEFile[];
    targetFolderId: string;
} | {
    kind: "draggingFolder";
    folderId: string;
    parentFolderId: string | null;
    previousState: CDEMachineState;
} | {
    kind: "movingFolder";
    folderId: string;
    targetFolderId: string | null;
} | {
    kind: "editingFolders";
    pendingChanges: FolderPendingChanges;
} | {
    kind: "savingFolderChanges";
    pendingChanges: FolderPendingChanges;
} | {
    kind: "editingFiles";
    pendingEdits: Record<string, Record<string, CDEMetadataValue>>;
    pendingArchives: string[];
    pendingRenames: Record<string, string>;
    previousState: {
        kind: "idle";
    } | {
        kind: "selected";
        files: CDEFile[];
    };
} | {
    kind: "savingFiles";
    pendingEdits: Record<string, Record<string, CDEMetadataValue>>;
    pendingArchives: string[];
    pendingRenames: Record<string, string>;
    previousState: {
        kind: "idle";
    } | {
        kind: "selected";
        files: CDEFile[];
    };
} | {
    kind: "error";
    reason: string;
    previous: CDEMachineState;
};
export type CDEMachineEvent = {
    type: "LOAD";
} | {
    type: "UPLOAD";
} | {
    type: "DOWNLOAD";
} | {
    type: "SELECT";
    files: CDEFile[];
} | {
    type: "DESELECT";
} | {
    type: "VIEW";
} | {
    type: "ADD_TO_VIEW";
    file: CDEFile;
} | {
    type: "REMOVE_FROM_VIEW";
    fileId: string;
} | {
    type: "CLOSE_VIEW";
} | {
    type: "SET_VIEW_FILE_STATUS";
    fileId: string;
    status: CDEViewFileStatus;
} | {
    type: "START_EDIT";
} | {
    type: "UPDATE_METADATA";
    key: string;
    value: CDEMetadataValue;
} | {
    type: "SAVE";
} | {
    type: "CANCEL_EDIT";
} | {
    type: "ARCHIVE_FILE";
} | {
    type: "START_CONFIGURE_METADATA_SCHEMA";
} | {
    type: "ADD_METADATA_FIELD";
} | {
    type: "UPDATE_METADATA_FIELD";
    key: string;
    value: CDEMetadataField;
} | {
    type: "DELETE_METADATA_FIELD";
    key: string;
} | {
    type: "RESTORE_METADATA_FIELD";
    key: string;
} | {
    type: "SAVE_METADATA_SCHEMA";
} | {
    type: "CANCEL_CONFIGURE_METADATA_SCHEMA";
} | {
    type: "START_DRAG";
    files: CDEFile[];
    sourceFolderId: string | null;
} | {
    type: "END_DRAG";
} | {
    type: "DROP_FILES";
    targetFolderId: string | null;
} | {
    type: "START_FOLDER_DRAG";
    folderId: string;
    parentFolderId: string | null;
} | {
    type: "END_FOLDER_DRAG";
} | {
    type: "DROP_FOLDER";
    targetFolderId: string | null;
} | {
    type: "START_EDIT_FILES";
} | {
    type: "UPDATE_FILE_METADATA";
    fileId: string;
    key: string;
    value: CDEMetadataValue;
} | {
    type: "REVERT_FILE_METADATA";
    fileId: string;
} | {
    type: "ARCHIVE_FILE_EDIT";
    fileId: string;
} | {
    type: "UNARCHIVE_FILE_EDIT";
    fileId: string;
} | {
    type: "RENAME_FILE";
    fileId: string;
    name: string;
} | {
    type: "RENAME_FILE_IMMEDIATE";
    fileId: string;
    name: string;
} | {
    type: "SAVE_FILE_EDITS";
} | {
    type: "CANCEL_EDIT_FILES";
} | {
    type: "START_EDIT_FOLDERS";
} | {
    type: "ADD_FOLDER";
    tempId: string;
    name: string;
    parentId: string | null;
} | {
    type: "RENAME_FOLDER";
    folderId: string;
    name: string;
} | {
    type: "ARCHIVE_FOLDER";
    folderId: string;
} | {
    type: "SAVE_FOLDER_CHANGES";
} | {
    type: "CANCEL_FOLDER_CHANGES";
} | {
    type: "RESET_FOLDER";
    folderId: string;
} | {
    type: "START_CONFIGURE_METADATA_VIEWS";
} | {
    type: "ADD_METADATA_VIEW";
} | {
    type: "UPDATE_METADATA_VIEW";
    id: string;
    view: CDEMetadataView;
} | {
    type: "DELETE_METADATA_VIEW";
    id: string;
} | {
    type: "SAVE_METADATA_VIEWS";
} | {
    type: "CANCEL_CONFIGURE_METADATA_VIEWS";
} | {
    type: "SET_ACTIVE_METADATA_VIEW";
    id: string | null;
} | {
    type: "SET_GROUPS_VIEW_MODE";
    mode: "groups" | "metadata";
} | {
    type: "FAIL";
    reason: string;
} | {
    type: "DISMISS";
};

declare class _CDEManager extends OBC.Component implements OBC.Transitionable<CDEMachineState, CDEMachineEvent> {
    static readonly uuid: "a3f82c1d-5b74-4e9a-bc30-d7e12f894a61";
    readonly onFilesChanged: OBC.Event<CDEFile[]>;
    readonly onFoldersChanged: OBC.Event<ItemFolder[]>;
    readonly onPermissionsChanged: OBC.Event<CDEUserPermissions>;
    readonly onSelectedGroupChanged: OBC.Event<string | null>;
    readonly onMachineStateChanged: OBC.Event<CDEMachineState>;
    readonly onMetadataViewsChanged: OBC.Event<CDEMetadataView[]>;
    readonly onGroupsViewModeChanged: OBC.Event<"groups" | "metadata">;
    readonly onMetadataGroupChanged: OBC.Event<Record<string, string> | null>;
    readonly onDownloadReady: OBC.Event<{
        blob: Blob;
        filename: string;
    }>;
    readonly onUploadCompleted: OBC.Event<{
        created: CDEFile[];
        versioned: CDEFile[];
    }>;
    readonly onFolderChangesCompleted: OBC.Event<{
        created: number;
        renamed: number;
        archived: number;
    }>;
    readonly onFilesMovedCompleted: OBC.Event<{
        files: CDEFile[];
        targetFolderName: string | null;
    }>;
    readonly onRenameCompleted: OBC.Event<{
        success: boolean;
        error?: string;
    }>;
    readonly onFolderMovedCompleted: OBC.Event<{
        folderName: string;
        targetFolderName: string | null;
    }>;
    readonly onShowArchivedChanged: OBC.Event<boolean>;
    readonly onRestoreCompleted: OBC.Event<{
        files?: CDEFile[];
        folder?: ItemFolder;
    }>;
    readonly onUploadStarted: OBC.Event<{
        count: number;
    }>;
    readonly onIfcConversionStarted: OBC.Event<{
        file: CDEFile;
    }>;
    readonly onIfcConversionProgress: OBC.Event<{
        file: CDEFile;
        progress: number;
    }>;
    readonly onIfcConversionCompleted: OBC.Event<{
        file: CDEFile;
        success: boolean;
        error?: string;
    }>;
    /** Fires when `_derivedFileIds` finishes a (re)sync — consumers that filter
     *  or resolve by source↔derived link (e.g. `top-files-panel` hiding an
     *  already-linked `.frag` row) should reload on this, since it can complete
     *  after `onFilesChanged` already fired with the (still unsynced) list. */
    readonly onDerivedFileIdsChanged: OBC.Event<Record<string, string>>;
    readonly conversionProgress: Map<string, number>;
    enabled: boolean;
    projectName: string;
    missingMetadataPlaceholder: string;
    availableColumns: Set<string>;
    visibleColumns: Set<string>;
    ctx?: CDEContext;
    private _machineState;
    private _activeUploads;
    private _showArchived;
    private _preArchivedViewMode;
    private _archivedFiles;
    private _archivedFolders;
    private _archivedLoaded;
    viewerGroups: {
        extensions: string[];
        multiple?: boolean;
    }[];
    get viewableExtensions(): Set<string>;
    private _files;
    /** ifcFileId → its linked derivedFileId (FRAG today; other source formats
     *  once they get a converter too), read from each IFC's own version
     *  metadata. Kept as an in-memory cache — synced by `_syncDerivedFileIds`
     *  whenever `_files` is (re)set, or right after a conversion succeeds —
     *  rather than fetched live per call, so `resolveViewFile` can stay a plain
     *  synchronous lookup (same contract as before, no ripple into
     *  `sendMachineEvent`'s callers). */
    private _derivedFileIds;
    private _folders;
    private _fileHistory;
    private _metadataSchema;
    private _metadataViews;
    private _activeMetadataViewId;
    private _groupsViewMode;
    private _selectedGroup;
    private _selectedMetadataGroup;
    private _namingSchema;
    cacheMaxBytes: number;
    cacheExtensions: Set<string>;
    private _fileCache;
    private _fileCacheBytes;
    private _dedup;
    private _cacheKey;
    private _isCacheable;
    private _addToCache;
    downloadFile(file: CDEFile): Promise<ArrayBuffer>;
    private _permissions;
    private _projectDataFolderId;
    private _appFolderIds;
    private _excludedFolderIds;
    private _projectMembers;
    get projectMembers(): {
        fullName: string;
        email: string;
        role: string;
    }[];
    get userPermissions(): CDEUserPermissions;
    query: string | null;
    get machineState(): CDEMachineState;
    get files(): CDEFile[];
    set files(value: CDEFile[]);
    /** ifcFileId → derivedFileId — see `_derivedFileIds`. */
    get derivedFileIds(): Record<string, string>;
    get folders(): ItemFolder[];
    set folders(value: ItemFolder[]);
    get showArchived(): boolean;
    set showArchived(value: boolean);
    get fileHistory(): CDEFileHistoryEntry[];
    set fileHistory(value: CDEFileHistoryEntry[]);
    get metadataSchema(): CDEMetadataSchema;
    set metadataSchema(value: CDEMetadataSchema);
    get selectedGroup(): string | null;
    set selectedGroup(value: string | null);
    get metadataViews(): CDEMetadataView[];
    get activeMetadataViewId(): string | null;
    get activeMetadataView(): CDEMetadataView | null;
    get groupsViewMode(): "groups" | "metadata";
    get selectedMetadataGroup(): Record<string, string> | null;
    set selectedMetadataGroup(value: Record<string, string> | null);
    get visibleFiles(): CDEFile[];
    get namingSchema(): CDENamingSchema | null;
    constructor(components: OBC.Components);
    hasViewer(extension: string): boolean;
    private _groupOf;
    private _sameGroup;
    canView(files: CDEFile[]): boolean;
    canAddToView(files: CDEFile[]): boolean;
    setNamingSchema(schema: CDENamingSchema): void;
    buildFileName(file: CDEFile): string;
    getSelectedFiles(): CDEFile[];
    getActivity(fileId: string): CDEFileActivity[];
    updateFilesMetadata(fileIds: string[], updates: Record<string, string>): Promise<void>;
    readProjectData(app: string, filename: string): Promise<any>;
    writeProjectData(app: string, filename: string, data: unknown): Promise<string>;
    private _ensureProjectDataFolder;
    private _ensureAppFolder;
    private _loadPermissions;
    loadFolders(): Promise<void>;
    createFolder(name: string, parentId?: string): Promise<ItemFolder>;
    getUserId(): Promise<string | undefined>;
    loadUserConfig(): Promise<{
        visibleColumns?: string[];
        metadataViews?: CDEMetadataView[];
        hideDerivedFiles?: boolean;
    } | null>;
    saveUserConfig(config: {
        visibleColumns?: string[];
        metadataViews?: CDEMetadataView[];
        hideDerivedFiles?: boolean;
    }): Promise<string | undefined>;
    loadMetadataSchema(): Promise<void>;
    initMetadataViews(views: CDEMetadataView[], activeId: string | null): void;
    loadArchivedItems(): Promise<void>;
    restoreFiles(files: CDEFile[]): Promise<void>;
    restoreFolder(folderId: string): Promise<void>;
    detectConflicts(files: File[]): {
        file: File;
        existing: CDEFile;
    }[];
    checkMoveConflicts(files: CDEFile[], targetFolderId: string | null): {
        file: CDEFile;
        existing: CDEFile;
    }[];
    /** Which file to actually load when the user views `file` — its linked FRAG
     *  if it has one, else the IFC itself. Reads `_derivedFileIds` (the IFC's
     *  own version metadata, kept in sync — see `_syncDerivedFileIds`), NOT a
     *  name+folder match anymore. Stays synchronous: `_derivedFileIds` is a
     *  pre-synced in-memory cache, so this is a plain lookup, keeping the
     *  contract every existing caller (`sendMachineEvent`'s `VIEW` case,
     *  `top-files-panel`'s "add to view" actions) already relies on. */
    resolveViewFile(file: CDEFile): CDEFile;
    /** Populates `_derivedFileIds` from every IFC's own version metadata — the
     *  source of truth for the IFC↔FRAG link (same mechanism as `models-list`'s
     *  `_syncDerivedFileIds`). Reads the unified `derivedFileId` key, falling
     *  back to the legacy `fragmentsFileId` key that `IfcFragmenter` still
     *  stamps until it's updated (see issue #3, Task 3). Called whenever
     *  `_files` is (re)set and right after a conversion succeeds — never
     *  cached indefinitely, so a reconversion or manual metadata edit is picked
     *  up on the next sync instead of going stale. */
    private _syncDerivedFileIds;
    private _saveConversionIndex;
    private _loadConversionIndex;
    private _resumePendingConversions;
    /** Cached id of the IfcFragmenter component, resolved by name for this session. */
    private _ifcFragmenterId?;
    /**
     * Resolves the platform IFC→FRAG cloud component's id by its stable name
     * (`IfcFragmenter`) within the current project, so it works across dev/prod
     * without a hardcoded id. Cached for the session. Returns `undefined` if no
     * such component is available in the project.
     */
    private _resolveIfcFragmenterId;
    private _triggerIfcConversions;
    uploadFiles(files: File[], folderId?: string | null, options?: {
        forceNew?: boolean;
    }): Promise<void>;
    sendMachineEvent(event: CDEMachineEvent): void;
    private _transition;
    private _getAllArchivedIds;
    private _collectTempDescendants;
    private _saveFolderChanges;
    private _moveFolder;
    moveFiles(files: CDEFile[], targetFolderId: string | null): Promise<void>;
    private _moveFiles;
    private _resolveFullName;
    private _prepareDownload;
    private _saveMetadataSchema;
    private _resolveKeys;
    private _saveFileMetadata;
    private _renameFileImmediate;
    private _saveFileEdits;
    private _applyMetadataEdits;
    private _applyMetadataSchemaEdits;
    private _saveMetadataViews;
    private _archiveFiles;
}

export type CDEManager = InstanceType<typeof _CDEManager>;
export const CDEManager = { uuid: 'a3f82c1d-5b74-4e9a-bc30-d7e12f894a61' } as typeof _CDEManager & { uuid: 'a3f82c1d-5b74-4e9a-bc30-d7e12f894a61' };

export type ClashStatus = "new" | "active" | "resolved" | "acknowledged";
export type ClashType = "hard" | "clearance";
export interface ClashElement {
    guid: string;
    name: string;
    localId: number;
    modelId: string;
}
export interface ClashQueryFilter {
    categories?: string[];
    attributes?: {
        aggregation?: 'exclusive' | 'inclusive';
        queries: Array<{
            name: string;
            value?: string | string[] | number | boolean;
            type?: string;
            negate?: boolean;
        }>;
    };
    relation?: {
        name: string;
        query?: ClashQueryFilter;
    };
}
export interface ClashQuery {
    id: string;
    name: string;
    modelFileIds: string[];
    /** Filter conditions. Omit or leave empty to match all elements with geometry. */
    query?: ClashQueryFilter;
}
export interface ClashMatrix {
    id: string;
    name: string;
    /** Ordered list of query IDs — index order = priority (0 = most constrained). */
    queryIds: string[];
    /** Active cell job IDs (subset of upper-triangle pairs). */
    jobIds: string[];
    /** Active upper-triangle pair keys in the form "queryAId:queryBId". */
    activePairs: string[];
    /** Clash type applied to all jobs generated by this matrix. Defaults to 'hard'. */
    jobType?: ClashType;
    /** Clearance tolerance in metres. Only used when jobType is 'clearance'. */
    tolerance?: number;
}
export interface ClashJob {
    id: string;
    name: string;
    type: ClashType;
    queryAId: string;
    queryBId: string;
    matrixId?: string;
    /** Clearance tolerance in metres. Only present when type is 'clearance'. */
    tolerance?: number;
}
export interface ClashRun {
    id: string;
    jobId: string;
    date: string;
    clashCount: number;
}
interface ClashBase {
    /** Deterministic FNV-1a hash of the normalized pair (elementA.guid, elementB.guid). Stable across runs. */
    id: string;
    jobId: string;
    firstSeenRunId: string;
    lastSeenRunId: string;
    elementA: ClashElement;
    elementB: ClashElement;
    point: [number, number, number];
    status: ClashStatus;
    comments?: string;
}
export interface HardClash extends ClashBase {
    type: "hard";
    volume?: number;
}
export interface ClearanceClash extends ClashBase {
    type: "clearance";
    distance: number;
}
export type Clash = HardClash | ClearanceClash;
export interface MarkerGroup {
    id?: string;
    point: [number, number, number];
    count: number;
    status?: ClashStatus;
}

/** `clashes.frag`'s path relative to `__project_data/`, for consumers that
 *  persist it via `projectStorageContext` instead of talking to `client`
 *  directly (see `buildClashBuffer`). */
export declare const CLASH_DATA_PATH = "collider/clashes.frag";
export interface ExecutionEntry {
    jobId: string;
    executionId: string;
    startedAt: string;
}
/** `cachedFileId`, when given, skips folder/file resolution (3 of the 4
 *  network round-trips this normally takes) — the file's ID never changes
 *  once created, so callers that already know it (see `ClashesManager`'s
 *  `_clashFragFileId`) should always pass it. */
export declare function ensureClashFragFileId(client: PlatformClient, projectId: string, cachedFileId?: string): Promise<string>;
export declare function getExecutions(client: PlatformClient, projectId: string | undefined): Promise<ExecutionEntry[]>;
export interface ClashData {
    jobs: ClashJob[];
    runs: ClashRun[];
    clashes: Clash[];
    queries: ClashQuery[];
    matrices: ClashMatrix[];
    /** Resolved once here — callers should cache and pass back into
     *  `loadClashData`/`buildClashBuffer` as `cachedFileId` to skip
     *  re-resolving it (see `ensureClashFragFileId`). */
    fileId: string;
}
export declare function loadClashData(client: PlatformClient, projectId: string, cachedFileId?: string): Promise<ClashData>;
/**
 * Diffs `data` against the persisted `clashes.frag` and builds the updated
 * buffer, WITHOUT uploading it — callers decide how/where to persist the
 * result (direct `client.updateFile`, via `projectStorageContext`, etc).
 * Still reads the current file via `client` to diff against (job/id
 * reconciliation needs the previous state), same as `saveClashData` always did.
 */
export declare function buildClashBuffer(client: PlatformClient, projectId: string, data: {
    queries: ClashQuery[];
    matrices: ClashMatrix[];
    jobs: ClashJob[];
    clashes: Clash[];
}, onJobsReconciled: (toAdd: ClashJob[], toRemove: Set<string>) => void, cachedFileId?: string): Promise<{
    blob: Blob;
    fileId: string;
}>;
/** Default persistence path: builds the buffer and uploads it straight to
 *  `client`. Kept as the manager's out-of-the-box behavior for any consumer
 *  that never overrides `ClashesManager.save` (e.g. doesn't route through
 *  `projectStorageContext`). */
export declare function saveClashData(client: PlatformClient, projectId: string, data: {
    queries: ClashQuery[];
    matrices: ClashMatrix[];
    jobs: ClashJob[];
    clashes: Clash[];
}, onJobsReconciled: (toAdd: ClashJob[], toRemove: Set<string>) => void): Promise<void>;


declare class _ClashesManager extends OBC.Component {
    static readonly uuid: "2c9f4e8d-3a1b-4c5e-9d7f-0a2b6c8e1d3f";
    enabled: boolean;
    readonly onQueriesChanged: OBC.Event<ClashQuery[]>;
    readonly onMatricesChanged: OBC.Event<ClashMatrix[]>;
    readonly onJobsChanged: OBC.Event<ClashJob[]>;
    readonly onRunsChanged: OBC.Event<ClashRun[]>;
    readonly onClashesChanged: OBC.Event<Clash[]>;
    readonly onClashStatusChanged: OBC.Event<Clash[]>;
    /** Dispara cuando empieza el debounce de guardado (pendiente de persistir). */
    readonly onSaveStart: OBC.Event<void>;
    /** Dispara al terminar el guardado. true = éxito, false = error. */
    readonly onSaveComplete: OBC.Event<boolean>;
    world?: OBC.World;
    /** Suprimir auto-save durante carga de datos (usar loadingData = true antes, false después). */
    loadingData: boolean;
    /** Registrar desde la app host para recargar datos desde el storage al terminar una ejecución. */
    reload?: () => Promise<void>;
    /** Registrar desde la app host para consultar qué jobIds tienen ejecución activa en storage. */
    checkExecutions?: () => Promise<Set<string>>;
    /** Registrar desde la app host para persistir queries y matrices al storage del proyecto. */
    save?: () => Promise<void>;
    /** Jobs con una ejecución cloud activa. Poblado por la app host al arrancar. */
    readonly runningJobIds: Set<string>;
    /** Mapa jobId → executionId para reconectar al WebSocket. Poblado por la app host al arrancar. */
    readonly activeExecutions: Map<string, string>;
    readonly onRunningJobsChanged: OBC.Event<Set<string>>;
    readonly onRunProgress: OBC.Event<{
        message: string;
        progress: number;
    }>;
    readonly onRunComplete: OBC.Event<{
        runId: string;
        clashCount: number;
    }>;
    readonly onRunError: OBC.Event<{
        code?: string;
        message: string;
    }>;
    readonly onReloadingChanged: OBC.Event<boolean>;
    isReloading: boolean;
    /** True once init(client) has been called — safe to call run(). */
    get ready(): boolean;
    private _client?;
    private _projectId?;
    /** `clashes.frag`'s file ID, resolved once by `init()`/`reload()`'s
     *  `loadClashData` call. Never changes once the file exists — passing it
     *  into `buildClashBuffer` skips 3 of its 4 network round-trips. */
    private _clashFragFileId?;
    private _reconnectingJobIds;
    private _queries;
    private _matrices;
    private _saveTimer?;
    private _savePromise?;
    private _jobs;
    private _runs;
    private _clashes;
    private _markers;
    private static _geo;
    get queries(): ClashQuery[];
    set queries(value: ClashQuery[]);
    get matrices(): ClashMatrix[];
    set matrices(value: ClashMatrix[]);
    private _scheduleSave;
    /** Chains onto any save already in flight instead of firing a second,
     *  concurrent `_doSave()` — two overlapping calls would race on
     *  `buildClashBuffer`'s read-diff-reconcile cycle (real network I/O;
     *  `onJobsReconciled` mutating `this.jobs` from two stale reads at once)
     *  and on the upload itself. It also keeps `flush()` correct: it just
     *  awaits `_savePromise`, so if that got overwritten by a newer, unrelated
     *  save instead of chained, flush() could resolve while an earlier save
     *  was still genuinely in flight. */
    private _queueSave;
    private _doSave;
    /** Cancela el debounce pendiente y ejecuta el save inmediatamente. Espera a que complete. */
    flush(): Promise<void>;
    /**
     * Builds the current `clashes.frag` buffer (diffed/reconciled against what's
     * persisted) WITHOUT uploading it. For consumers (e.g. `clashes-panel`) that
     * override `save` to persist via `projectStorageContext` instead of the
     * default direct-`client` path.
     */
    buildClashBuffer(): Promise<Blob>;
    get jobs(): ClashJob[];
    set jobs(value: ClashJob[]);
    get runs(): ClashRun[];
    set runs(value: ClashRun[]);
    get clashes(): Clash[];
    set clashes(value: Clash[]);
    queryById(id: string): ClashQuery | undefined;
    private _clashStylesRegistered;
    /** Green — elementA's highlight color. Public so consumers (e.g. "create
     *  topic from clash") can build a matching BCF viewpoint `componentColors`
     *  entry without duplicating the hex value. */
    readonly STYLE_A = "#22c55e";
    /** Red — elementB's highlight color. Same reasoning as `STYLE_A`. */
    readonly STYLE_B = "#ef4444";
    private _clashStyle;
    highlightAllClashes(clashes: Clash[]): void;
    ghostClashes(clashes: Clash[]): Promise<void>;
    ghostClash(clash: Clash): Promise<void>;
    clearGhostClash(): Promise<void>;
    highlightClash(clash: Clash): void;
    clearClashHighlight(): void;
    showMarkers(groups: MarkerGroup[]): void;
    hideMarkers(): void;
    toViewerPoint(point: [number, number, number]): THREE.Vector3;
    private _toViewer;
    private _renderMarkers;
    private _clearMarkers;
    cluster(clashes: Clash[], threshold: number): Clash[][];
    private _setHighlighterEnabled;
    private _isolatedMaterials;
    runsForJob(jobId: string): ClashRun[];
    clashesForRun(runId: string): Clash[];
    updateClash(id: string, changes: {
        status?: ClashStatus;
        comments?: string;
    }): void;
    /**
     * Initializes the manager from cloud storage: loads clash data, wires save/reload,
     * reads in-flight executions, and resolves the viewer world (non-blocking).
     * Consumer apps call this once instead of wiring all the pieces manually.
     */
    init(client: PlatformClient): Promise<void>;
    /** Launches clash detection in a Web Worker. Fires onRunProgress/onRunComplete/onRunError. */
    run(jobId: string): void;
    private _handleWorkerComplete;
    /** Reconnects to an in-flight execution when the user opens a job that was running before page load. */
    reconnectIfRunning(jobId: string): void;
    private _listenToExecution;
    private _firstWorld;
}

export type ClashesManager = InstanceType<typeof _ClashesManager>;
export const ClashesManager = { uuid: '2c9f4e8d-3a1b-4c5e-9d7f-0a2b6c8e1d3f' } as typeof _ClashesManager & { uuid: '2c9f4e8d-3a1b-4c5e-9d7f-0a2b6c8e1d3f' };

/**
 * Which action buttons to expose per file row. All default to `true`.
 */
export interface FileListActions {
    download?: boolean;
    rename?: boolean;
    delete?: boolean;
}
/**
 * Config passed to {@link FileList.create}.
 */
export interface FileListConfig {
    /** Services client used to list and mutate files. */
    client: EngineServicesClient;
    /** Optional folder ID to scope the list. If omitted, lists root files. */
    folderId?: string;
    /** Which action buttons to show per row. Defaults to all enabled. */
    actions?: FileListActions;
    /** Called when a file row is clicked (not an action button). */
    onFileClick?: (file: Item) => void;
}
/**
 * The result returned by {@link FileList.create}.
 */
export interface FileListInstance {
    /** The DOM element to mount somewhere in your layout. */
    element: HTMLElement;
    /** Reloads the list from the services client. */
    refresh: () => Promise<void>;
    /** Changes the folder scope and reloads. Pass `undefined` for the root. */
    setFolder: (folderId?: string) => Promise<void>;
    /** Removes the element and forgets the instance. */
    dispose: () => void;
}

/**
 * Built-in component that renders a file list backed by the services client,
 * with built-in download / rename / delete actions.
 *
 * The backing data comes from {@link EngineServicesClient.listFiles}, so the
 * list stays in sync with the storage service. Each call to {@link create}
 * returns an independent instance with its own DOM element.
 *
 * @example
 * ```ts
 * const fileList = components.get(FileList);
 * const { element, refresh } = fileList.create({
 *   client: app.client,
 *   folderId: someFolderId,
 * });
 * container.appendChild(element);
 * ```
 */
declare class _FileList extends OBC.Component {
    static readonly uuid: "b0b5e2a2-0b3a-4a6b-8b1c-0b1c4a6b8b1c";
    enabled: boolean;
    readonly name = "FileList";
    private _instances;
    /**
     * Creates a new file-list instance. Returns the DOM element to mount plus a
     * `refresh` handle to reload the list, a `setFolder` to change scope, and a
     * `dispose` to remove it.
     */
    create(config: FileListConfig): FileListInstance;
    /**
     * Removes every instance this manager has created.
     */
    dispose(): void;
}

/**
 * Built-in component that renders a file list backed by the services client,
 * with built-in download / rename / delete actions.
 *
 * The backing data comes from {@link EngineServicesClient.listFiles}, so the
 * list stays in sync with the storage service. Each call to {@link create}
 * returns an independent instance with its own DOM element.
 *
 * @example
 * ```ts
 * const fileList = components.get(FileList);
 * const { element, refresh } = fileList.create({
 *   client: app.client,
 *   folderId: someFolderId,
 * });
 * container.appendChild(element);
 * ```
 */
export type FileList = InstanceType<typeof _FileList>;
/**
 * Built-in component that renders a file list backed by the services client,
 * with built-in download / rename / delete actions.
 *
 * The backing data comes from {@link EngineServicesClient.listFiles}, so the
 * list stays in sync with the storage service. Each call to {@link create}
 * returns an independent instance with its own DOM element.
 *
 * @example
 * ```ts
 * const fileList = components.get(FileList);
 * const { element, refresh } = fileList.create({
 *   client: app.client,
 *   folderId: someFolderId,
 * });
 * container.appendChild(element);
 * ```
 */
export const FileList = { uuid: 'b0b5e2a2-0b3a-4a6b-8b1c-0b1c4a6b8b1c' } as typeof _FileList & { uuid: 'b0b5e2a2-0b3a-4a6b-8b1c-0b1c4a6b8b1c' };

/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
declare class _HelloWorld extends OBC.Component {
    static readonly uuid: "2c4ae432-fc24-43e9-9783-0c960c674e96";
    enabled: boolean;
    readonly name = "HelloWorld";
    constructor(components: OBC.Components);
    /**
     * Returns a greeting message and logs it to the console.
     * @param who - The name to greet. Defaults to `"World"`.
     */
    greet(who?: string): string;
}
/**
 * PlatformComponents.import() expects a `main` variable in scope with
 * a `componentDefinition` property pointing to the OBC.Component class.
 * The IIFE build (name: 'main') assigns this to `var main = ...`.
 */

/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
export type HelloWorld = InstanceType<typeof _HelloWorld>;
/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
export const HelloWorld = { uuid: '2c4ae432-fc24-43e9-9783-0c960c674e96' } as typeof _HelloWorld & { uuid: '2c4ae432-fc24-43e9-9783-0c960c674e96' };

/** `main.bcf`'s path relative to `__project_data/` — shared with
 *  `requestBcfSave` (`UIManager/src/utils/bcf-storage.ts`) so both sides of
 *  the save/load round-trip agree on where the file lives. */
export declare const BCF_DATA_PATH = "topics/main.bcf";
/** Downloads `__project_data/topics/main.bcf` and loads it into `BCFTopics`,
 *  if it already has content. A freshly-created file is empty (0 bytes) —
 *  not a valid BCF zip — so there's nothing to load yet in that case. */
export declare function loadBcfTopics(client: PlatformClient, projectId: string, components: OBC.Components): Promise<void>;


/**
 * Wires up everything `top-topics-panel` (and `clashes-panel`'s "create
 * topic from clash" feature) needs to work out of the box: `BCFTopics`
 * configuration (version, author, assignable users — all from real project
 * data), loading whatever BCF was previously saved for this project, and
 * resolving `Viewpoints.world` — including backfilling it onto viewpoints
 * restored from a saved BCF before the 3D world existed yet (`top-viewer`
 * only creates its `World` once `top-app` finishes mounting, which is later
 * than `init()` typically runs).
 */
declare class _TopicsManager extends OBC.Component {
    static readonly uuid: "69af63aa-19ba-4fc7-b17b-75647bac1d76";
    enabled: boolean;
    /**
     * Consumer apps call this once — same pattern as `ClashesManager.init(client)`
     * — instead of wiring `BCFTopics.setup()`, loading the saved BCF, and
     * backfilling viewpoint worlds by hand.
     */
    init(client: PlatformClient): Promise<void>;
    private _firstWorld;
}

/**
 * Wires up everything `top-topics-panel` (and `clashes-panel`'s "create
 * topic from clash" feature) needs to work out of the box: `BCFTopics`
 * configuration (version, author, assignable users — all from real project
 * data), loading whatever BCF was previously saved for this project, and
 * resolving `Viewpoints.world` — including backfilling it onto viewpoints
 * restored from a saved BCF before the 3D world existed yet (`top-viewer`
 * only creates its `World` once `top-app` finishes mounting, which is later
 * than `init()` typically runs).
 */
export type TopicsManager = InstanceType<typeof _TopicsManager>;
/**
 * Wires up everything `top-topics-panel` (and `clashes-panel`'s "create
 * topic from clash" feature) needs to work out of the box: `BCFTopics`
 * configuration (version, author, assignable users — all from real project
 * data), loading whatever BCF was previously saved for this project, and
 * resolving `Viewpoints.world` — including backfilling it onto viewpoints
 * restored from a saved BCF before the 3D world existed yet (`top-viewer`
 * only creates its `World` once `top-app` finishes mounting, which is later
 * than `init()` typically runs).
 */
export const TopicsManager = { uuid: '69af63aa-19ba-4fc7-b17b-75647bac1d76' } as typeof _TopicsManager & { uuid: '69af63aa-19ba-4fc7-b17b-75647bac1d76' };

declare class _UIManager extends OBC.Component {
    #private;
    static readonly uuid: "234f1416-528d-452a-9cc9-a16c5239b2eb";
    enabled: boolean;
    readonly name = "UIManager";
    init(): void;
}

export type UIManager = InstanceType<typeof _UIManager>;
export const UIManager = { uuid: '234f1416-528d-452a-9cc9-a16c5239b2eb' } as typeof _UIManager & { uuid: '234f1416-528d-452a-9cc9-a16c5239b2eb' };
